## Time-stamp: <2014-12-30 13:42:14 vk>
## -*- coding: utf-8; mode: org; -*-
## This file is best viewed with GNU Emacs Org-mode: http://orgmode.org/


* README

This file contains the format templates of your blog.

lazyblorg needs a template file (command line parameter ~--template~)
which holds the output format definitions. It is using (only) the
heading which meets *all* of the following requirements:

- named ~Templates~
- is marked as ~DONE~
- tagged with ~:blog:~
- contains the unique ID property ~lazyblorg-templates~
- contains a ~:LOGBOOK:~ drawer with a time-stamp for being set to a
  ~DONE~ state

(Besides the name ~Templates~ those are the very same criteria for a
blog entry in general, by the way.)

This way, you can switch between different formats by using different
files (using different template files) or different headings within
this file (renaming first level headings and IDs; not recommended),
respectively.

The format templates are located in a heading hierarchy within the
~Templates~ heading. The hierarchy should be self explaining for
you. Please *do not modify headings* since lazyblorg is looking for
their exact form - at least for the first two levels.

Within a heading, each format template is defined in a HTML [[http://orgmode.org/manual/Working-With-Source-Code.html#Working-With-Source-Code][babel
block]].  Its name corresponds to the internal lazyblorg definition. So
please *do not modify the name strings* otherwise lazyblorg gets very
sad!

Within a format template, you will see strings like ~#FOO#~. These
place holder strings will get replaced by your content. If you modify
those, lazyblorg is not able to replace them with your content: *do
not modify/remove/invent place holder strings* by yourself.

In between the format templates, you can write whatever you want
unless it is no babel block of type ~html~: lazyblorg will ignore
these in-between notes.

For documentation about the implemented elements: see
id:implemented-org-elements in [[file:../dev/lazyblorg.org]]

Have fun with modifying lazyblorg to your requirements!

* DONE Templates                                                                  :lb_templates:blog:
:PROPERTIES:
:CREATED:  [2014-12-26 Fri 16:09]
:END:
:LOGBOOK:
- State "DONE"       from "DONE"       [2013-08-21 Wed 17:50]
:END:
:PROPERTIES:
:ID: lazyblorg-templates
:CREATED:  [2013-08-21 Wed 17:50]
:END:

** General elements

*** Sidebar

#+NAME: common-sidebar
#+BEGIN_HTML

  <div class="sidebar">
     <div class="search">
       <iframe src="http://duckduckgo.com/search.html?width=140&site=karl-voit.at&prefill=Search blog" frameborder="0"></iframe><br/>
     </div>
     <ul>
     <li>TBD: Archive</li>
     <li><a href="/">Recent articles</a></li>
     <li>[[id:2014-03-09-about][About this blog]]</li>
     <li>TBD: How to use this blog efficiently</li>
     <li><a href="http://karl-voit.at/feeds/lazyblorg-all.atom_1.0.links-only.xml">Follow/subscribe links</a></li>
     <li><a href="http://karl-voit.at/feeds/lazyblorg-all.atom_1.0.links-and-content.xml">Follow/subscribe content</a></li>
     <li>TBD: Per Tag Feeds</li>
     </ul>
  </div>

#+END_HTML

*** Sections

- #SECTION-TITLE#: title of the next heading/section
- #SECTION-LEVEL#: relative level of the next heading/section

#+NAME: section-begin
#+BEGIN_HTML

	  <header><h#SECTION-LEVEL# class="section-title">#SECTION-TITLE#</h#SECTION-LEVEL#></header>

#+END_HTML
*** Paragraph

- #PAR-CONTENT#

#+NAME: paragraph
#+BEGIN_HTML

<p>

#PAR-CONTENT#

</p>

#+END_HTML

*** Lists

#+NAME: ul-begin
#+BEGIN_HTML
	  <ul>
#+END_HTML

- #CONTENT#: text of the list item

#+NAME: ul-item
#+BEGIN_HTML
	    <li>#CONTENT#</li>
#+END_HTML

#+NAME: ul-end
#+BEGIN_HTML
	  </ul>
#+END_HTML

*** Pre-formatted text

Without name/label:

#+NAME: pre-begin
#+BEGIN_HTML

	  <pre>
#+END_HTML

#+NAME: pre-end
#+BEGIN_HTML
	  </pre>

#+END_HTML

With name/label:

#+NAME: named-pre-begin
#+BEGIN_HTML

<p>

    #NAME#
	  <pre>
#+END_HTML

#+NAME: named-pre-end
#+BEGIN_HTML
	  </pre>

</p>
#+END_HTML

*** SRC blocks (not HTML)

Without name/label:

#+NAME: src-begin
#+BEGIN_HTML

	  <div class="example_code">
	  <pre>
#+END_HTML

#+NAME: src-end
#+BEGIN_HTML
	  </pre>
    </div>

#+END_HTML

With name/label:

#+NAME: named-src-begin
#+BEGIN_HTML

<p>

    #NAME#
	  <div class="example_code">
	  <pre>
#+END_HTML

#+NAME: named-src-end
#+BEGIN_HTML
	  </pre>
    </div>

</p>
#+END_HTML

*** HTML blocks

- #NAME#: Org-mode name of the block

#+NAME: html-begin
#+BEGIN_HTML

<p>

    #NAME#
	  <div class="example_code">
#+END_HTML

#+NAME: html-end
#+BEGIN_HTML
	  </div>

</p>

#+END_HTML

*** QUOTE blocks

#+NAME: blockquote-begin
#+BEGIN_HTML

<blockquote>
#+END_HTML

#+NAME: blockquote-end
#+BEGIN_HTML
</blockquote>

#+END_HTML

*** ignore me

#+NAME:
#+BEGIN_HTML
#+END_HTML

#+NAME:
#+BEGIN_HTML
#+END_HTML


** Persistent

*** Entry Page

**** Header

- #BLOGNAME#: short name of the blog
- #ABOUT-BLOG#: a line of text which describes the blog in general
- #COMMON-SIDEBAR# : the sidebar conentent which is shared on all pages


#+NAME: entrypage-header
#+BEGIN_HTML
  <!DOCTYPE html>
  <html xmlns="http://www.w3.org/1999/xhtml">
  <meta charset="UTF-8">
  <meta name="author" content="Karl Voit" />
  <meta name="generator" content="lazyblorg" />
  <link rel="stylesheet" title="public voit Standard CSS Style"
        href="http://Karl-Voit.at/public_voit.css" type="text/css" media="screen"  />

  <!-- WARNING: This page is written in HTML5 and might not be displayed correctly in old browsers. -->

  <body class="persistent-body">

  <header class="persistent-header">

      <nav class="entrypage-article-header-nav">
        <span class="breadcrumbs">
          <img src="http://karl-voit.at/images/public-voit_logo.svg" alt="public voit logo" width="350" style="vertical-align:middle;"><span style="padding-top:1em;">
        </span>
      </nav>
    
  </header>

  #COMMON-SIDEBAR#

  <div class="entry-page-greetings">
  <p>

    This is the home-page of Karl Voit. 

  </p>

  <p>

    Please notice: <a href="2014/01/30/public-voit-beta/">This site is under constant development</a>. See 
    <a href="https://github.com/novoid/lazyblorg/blob/master/dev/lazyblorg.org#23-implemented-org-mode-elements">current status of the blogging software</a> and 
    <a href="https://github.com/novoid/lazyblorg/blob/master/dev/lazyblorg.org#1-issue-tracking">the next steps</a>.
  </p>

  <p>

    Recent articles/updates:

  </p>
  </div>

#+END_HTML

**** Article-Preview

- #ARTICLE-TITLE#: heading/title of the blog article
- #ARTICLE-URL#: URL of the blog article
- #ARTICLE-YEAR#: four digit year of the article (folder path)
- #ARTICLE-MONTH#: two digit month of the article (folder path)
- #ARTICLE-DAY#: two digit day of the article (folder path)
- #ARTICLE-PUBLISHED-HTML-DATETIME#: time-stamp of publishing in HTML
  date-time format (e.g., ~2011-10-30T15:00+02:00~)
- #ARTICLE-PUBLISHED-HUMAN-READABLE#: time-stamp of publishing in
  human readable format (e.g., ~2011-10-30T15:00~)
- #ARTICLE-TEASER#: First lines up to the first heading or <hr>-element

#+NAME: article-preview-header
#+BEGIN_HTML


<article class="entry-page-article"> 
#+END_HTML

#+NAME: article-preview-tags-begin
#+BEGIN_HTML

	  <aside>
	    <ul class="entry-page-article-tags">
#+END_HTML

- #TAGNAME#: string of a tag

#+NAME: article-preview-tag
#+BEGIN_HTML
	      <!-- span class="tag">#TAGNAME#</span>&nbsp;-->
        <li><a href="#">#TAGNAME#</a></li>
#+END_HTML

#+NAME: article-preview-tags-end
#+BEGIN_HTML

	    </ul>
	  </aside>
#+END_HTML


#+NAME: article-preview-begin
#+BEGIN_HTML

<h1><a href="#ARTICLE-URL#">#ARTICLE-YEAR#-#ARTICLE-MONTH#-#ARTICLE-DAY#: #ARTICLE-TITLE#</a></h1>

#ARTICLE-TEASER#

#+END_HTML

#+NAME: article-preview-more
#+BEGIN_HTML
<p>
<a href="#ARTICLE-URL#" class="article-preview-more">Read the whole article&nbsp;...</a>
</p>
#+END_HTML

#+NAME: article-preview-end
#+BEGIN_HTML


</article> 


#+END_HTML

**** Footer

- #BLOGNAME#: short name of the blog
- #ABOUT-BLOG#: a line of text which describes the blog in general

#+NAME: entrypage-footer
#+BEGIN_HTML


    <footer>
      <p><i>[[id:2014-03-09-about][#ABOUT-BLOG#]]</i> is authored in <a href="http://orgmode.org">Org-mode</a> and generated by <a href="https://github.com/novoid/lazyblorg">lazyblorg</a>

	 	&nbsp;&bull;&nbsp; <a href="http://validator.w3.org/check/referer">HTML5</a>

	 	&nbsp;&bull;&nbsp; <a href="http://jigsaw.w3.org/css-validator/">CSS3</a>
      </p>
    </footer>

  </body>
</html>
#+END_HTML


*** Other Persistent Pages

**** Header

- #ARTICLE-TITLE#: heading/title of the blog article

#+NAME: persistent-header
#+BEGIN_HTML
  <!DOCTYPE html>
  <html xmlns="http://www.w3.org/1999/xhtml">
  <meta charset="UTF-8">
  <meta name="author" content="Karl Voit" />
  <meta name="generator" content="lazyblorg" />
  <link rel="stylesheet" title="public voit Standard CSS Style"
        href="http://Karl-Voit.at/public_voit.css" type="text/css" media="screen"  />

  <!-- WARNING: This page is written in HTML5 and might not be displayed correctly in old browsers. -->

    <head>
      <title>#ARTICLE-TITLE#</title>
      
    </head>

#+END_HTML

**** Top of Article

- #BLOGNAME#: short name of the blog
- #ARTICLE-YEAR#: four digit year of the article (folder path)
- #ARTICLE-MONTH#: two digit month of the article (folder path)
- #ARTICLE-DAY#: two digit day of the article (folder path)
- #ARTICLE-PUBLISHED-HTML-DATETIME#: time-stamp of publishing in HTML
  date-time format (e.g., 2011-10-30T15:00+02:00)
- #ARTICLE-PUBLISHED-HUMAN-READABLE#: time-stamp of publishing in
  human readable format (e.g., 2011-10-30T15:00)
- #COMMON-SIDEBAR# : the sidebar conentent which is shared on all pages

#+NAME: persistent-header-begin
#+BEGIN_HTML
  <body>

    <div class="common-orgsource"><a href="source.org.txt">&#960;</a></div>

	<header>

	  <nav class="persistent-article-header-nav">
	    <span class="breadcrumbs">
	      <a href="../"><img src="http://karl-voit.at/images/public-voit_logo.svg" alt="public voit logo" width="350" style="vertical-align:middle;"></a>
	    </span>
	  </nav>

#+END_HTML

#+NAME: persistent-header-end
#+BEGIN_HTML

	  <h1 class="common-article-header-title">#ARTICLE-TITLE#</h1>

	</header>

    #COMMON-SIDEBAR#

    <article class="common-article">

#+END_HTML

#+NAME: persistent-end
#+BEGIN_HTML

    </article>

#+END_HTML

**** Footer

- #ABOUT-BLOG#: a line of text which describes the blog in general

#+NAME: persistent-footer
#+BEGIN_HTML
	  <aside class="published-on">
	    Published on <time datetime="#ARTICLE-PUBLISHED-HTML-DATETIME#">#ARTICLE-PUBLISHED-HUMAN-READABLE#</time>
	  </aside>

   <p class="email-comment">
      <a href="mailto:publicvoit-comment@Karl-Voit.at?subject=#ARTICLE-ID# comment: &body=Please do not remove '#ARTICLE-ID# comment:' in subject and please tell me whether or not it is OK to add your comment and/or your email address to the blog entry!">Comment via email</a> or via <a href="http://disqus.com">Disqus</a> comments below:
   </p>

    <div id="disqus_thread"></div>
    <div id="disqus_loader" style="text-align: center">
      <!-- stolen from http://blog.yjl.im/2012/04/let-your-readers-decide-when-to-load.html -->
      <button onclick="load_disqus()">Load Disqus Comments</button>
      <script>
        function load_disqus()
        {
          var dsq = document.createElement('script'); 
          dsq.type = 'text/javascript'; 
          dsq.async = true;
          dsq.src = "http://publicvoit.disqus.com/embed.js";
          var disqus_identifier = '#ARTICLE-ID#';
          (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
          var ldr = document.getElementById('disqus_loader');
          ldr.parentNode.removeChild(ldr);
        }
      </script>
    </div>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">Disqus comments.</a></noscript>
    
    <footer>
      <p><i>[[id:2014-03-09-about][#ABOUT-BLOG#]]</i> is authored in <a href="http://orgmode.org">Org-mode</a> and generated by <a href="https://github.com/novoid/lazyblorg">lazyblorg</a>

	 	&nbsp;&bull;&nbsp; <a href="http://validator.w3.org/check/referer">HTML5</a>

	 	&nbsp;&bull;&nbsp; <a href="http://jigsaw.w3.org/css-validator/">CSS3</a>
      </p>
    </footer>

  </body>
</html>
#+END_HTML


** Article

*** Header

- #ARTICLE-TITLE#: heading/title of the blog article

#+NAME: article-header
#+BEGIN_HTML
  <!DOCTYPE html>
  <html xmlns="http://www.w3.org/1999/xhtml">
  <meta charset="UTF-8">
  <meta name="author" content="Karl Voit" />
  <meta name="generator" content="lazyblorg" />
  <link rel="stylesheet" title="public voit Standard CSS Style"
        href="http://Karl-Voit.at/public_voit.css" type="text/css" media="screen"  />

  <!-- WARNING: This page is written in HTML5 and might not be displayed correctly in old browsers. -->

    <head>
      <!-- link rel="stylesheet" type="text/css" href="../../../../style.css" / -->
      <title>#ARTICLE-TITLE#</title>
      
    </head>
#+END_HTML

*** Top of Article

- #BLOGNAME#: short name of the blog
- #ARTICLE-YEAR#: four digit year of the article (folder path)
- #ARTICLE-MONTH#: two digit month of the article (folder path)
- #ARTICLE-DAY#: two digit day of the article (folder path)
- #ARTICLE-PUBLISHED-HTML-DATETIME#: time-stamp of publishing in HTML
  date-time format (e.g., 2011-10-30T15:00+02:00)
- #ARTICLE-PUBLISHED-HUMAN-READABLE#: time-stamp of publishing in
  human readable format (e.g., 2011-10-30T15:00)
- #COMMON-SIDEBAR# : the sidebar conentent which is shared on all pages

#+NAME: article-header-begin
#+BEGIN_HTML
  <body>

    <div class="common-orgsource"><a href="source.org.txt">&#960;</a></div>


	<header>

	  <nav class="temporal-article-header-nav">
	    <span class="breadcrumbs">
	      <a href="../../../../"><img src="http://karl-voit.at/images/public-voit_logo.svg" alt="public voit logo" width="350" style="vertical-align:middle;"></a><span style="padding-top:1em;">&nbsp;&nbsp;&nbsp;&nbsp;&raquo;
	      #ARTICLE-YEAR#&nbsp;&ndash;&nbsp;#ARTICLE-MONTH#&nbsp;&ndash;&nbsp;#ARTICLE-DAY#</span>
	      <!-- a href="../../../">#ARTICLE-YEAR#</a>&nbsp;&ndash;&nbsp;<a href="../../">#ARTICLE-MONTH#</a>&nbsp;&ndash;&nbsp;<a href="../">#ARTICLE-DAY#</a -->
	    </span>
	  </nav>

#+END_HTML


#+NAME: article-tags-begin
#+BEGIN_HTML
	  <aside class="common-tags">
	    <ul>
#+END_HTML

- #TAGNAME#: string of a tag

#+NAME: article-tag
#+BEGIN_HTML
	      <!-- span class="tag">#TAGNAME#</span>&nbsp;-->
        <li><a href="#">#TAGNAME#</a></li>
#+END_HTML

#+NAME: article-tags-end
#+BEGIN_HTML
	    </ul>
	  </aside>
#+END_HTML

#+NAME: article-header-end
#+BEGIN_HTML

	  <h1 class="common-article-header-title">#ARTICLE-TITLE#</h1>

	</header>

  #COMMON-SIDEBAR#

  <article class="common-article">

#+END_HTML

#+NAME: article-end
#+BEGIN_HTML


  </article>

#+END_HTML

*** Footer

- #ABOUT-BLOG#: a line of text which describes the blog in general

#+NAME: article-footer
#+BEGIN_HTML
	  <aside class="published-on">
	    Published on <time datetime="#ARTICLE-PUBLISHED-HTML-DATETIME#">#ARTICLE-PUBLISHED-HUMAN-READABLE#</time>
	  </aside>

   <p class="email-comment">
      <a href="mailto:publicvoit-comment@Karl-Voit.at?subject=#ARTICLE-ID# comment: &body=Please do not remove '#ARTICLE-ID# comment:' in subject and please tell me whether or not it is OK to add your comment and/or your email address to the blog entry!">Comment via email</a> or via <a href="http://disqus.com">Disqus</a> comments below:
   </p>

    <div id="disqus_thread"></div>
    <div id="disqus_loader" style="text-align: center">
      <!-- stolen from http://blog.yjl.im/2012/04/let-your-readers-decide-when-to-load.html -->
      <button onclick="load_disqus()">Load Disqus Comments</button>
      <script>
        function load_disqus()
        {
          var dsq = document.createElement('script'); 
          dsq.type = 'text/javascript'; 
          dsq.async = true;
          dsq.src = "http://publicvoit.disqus.com/embed.js";
          var disqus_identifier = '#ARTICLE-ID#';
          (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
          var ldr = document.getElementById('disqus_loader');
          ldr.parentNode.removeChild(ldr);
        }
      </script>
    </div>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">Disqus comments.</a></noscript>
    
    <footer>
      <p><i>[[id:2014-03-09-about][#ABOUT-BLOG#]]</i> is authored in <a href="http://orgmode.org">Org-mode</a> and generated by <a href="https://github.com/novoid/lazyblorg">lazyblorg</a>

	 	&nbsp;&bull;&nbsp; <a href="http://validator.w3.org/check/referer">HTML5</a>

	 	&nbsp;&bull;&nbsp; <a href="http://jigsaw.w3.org/css-validator/">CSS3</a>
      </p>
    </footer>

  </body>
</html>
#+END_HTML


** Tags

FIXXME

** Day Overview

FIXXME

** Month Overview

*** Header

- #BLOGNAME#: short name of the blog
- #YEAR#: four digit year
- #MONTH-LONGNAME#: name of the month like "Jannuary" or "February"
- #MONTH-SHORTNAME#: three letter name of the month like "Jan" or "Feb"
- #MONTH-TWODIGITNUMBER#: number of the month like "01" or "02"

#+NAME: month-header
#+BEGIN_HTML
  <!DOCTYPE html>
  <html xmlns="http://www.w3.org/1999/xhtml">
  <meta charset="UTF-8">
  <meta name="author" content="Karl Voit" />
  <meta name="generator" content="lazyblorg" />
  <link rel="stylesheet" title="public voit Standard CSS Style"
        href="http://Karl-Voit.at/public_voit.css" type="text/css" media="screen"  />

  <!-- WARNING: This page is written in HTML5 and might not be displayed correctly in old browsers. -->

    <head>
      <title>#BLOGNAME#: #YEAR#-#MONTH-TWODIGITNUMBER#</title>
    </head>

  <body>

  <article class="month-overview">

	<header>

	  <nav class="month-overview-header-nav">
	    <span class="breadcrumbs">
	      <a href="../../"><img src="http://karl-voit.at/images/public-voit_logo.svg" alt="public voit logo" width="350" style="vertical-align:middle;"></a><span style="padding-top:1em;">&nbsp;&nbsp;&nbsp;&nbsp;&raquo;
	      #YEAR#&nbsp;&ndash;&nbsp;#MONTH-TWODIGITNUMBER#</span>
	    </span>
	  </nav>

	  <h1 class="article-title">#YEAR#-#MONTH-TWODIGITNUMBER#</h1>

	</header>

  <p><ul class="month-body">

#+END_HTML

*** Article-Link

- #ARTICLE-TITLE#: heading/title of the blog article
- #ARTICLE-URL#: URL of the blog article
- #ARTICLE-YEAR#: four digit year of the article (folder path)
- #ARTICLE-MONTH#: two digit month of the article (folder path)
- #ARTICLE-DAY#: two digit day of the article (folder path)
- #ARTICLE-PUBLISHED-HTML-DATETIME#: time-stamp of publishing in HTML
  date-time format (e.g., 2011-10-30T15:00+02:00)
- #ARTICLE-PUBLISHED-HUMAN-READABLE#: time-stamp of publishing in
  human readable format (e.g., 2011-10-30T15:00)

#+NAME: article-list-link
#+BEGIN_HTML
<li><a href="#ARTICLE-URL#">#ARTICLE-YEAR#-#ARTICLE-MONTH#-#ARTICLE-DAY#: #ARTICLE-TITLE#</a></li>
#+END_HTML

*** Footer

- #BLOGNAME#: short name of the blog
- #YEAR#: four digit year
- #MONTH-LONGNAME#: name of the month like "Jannuary" or "February"
- #MONTH-SHORTNAME#: three letter name of the month like "Jan" or "Feb"
- #MONTH-TWODIGITNUMBER#: number of the month like "01" or "02"

#+NAME: month-footer
#+BEGIN_HTML

    </ul></p>
    </article>

    <footer>
      <p><i>[[id:2014-03-09-about][#ABOUT-BLOG#]]</i> is authored in <a href="http://orgmode.org">Org-mode</a> and generated by <a href="https://github.com/novoid/lazyblorg">lazyblorg</a>

	 	&nbsp;&bull;&nbsp; <a href="http://validator.w3.org/check/referer">HTML5</a>

	 	&nbsp;&bull;&nbsp; <a href="http://jigsaw.w3.org/css-validator/">CSS3</a>
      </p>
    </footer>

  </body>
</html>
#+END_HTML
** Year Overview

FIXXME

* Local Variables                                                                          :noexport:
:PROPERTIES:
:CREATED:  [2014-12-26 Fri 16:09]
:END:
# Local Variables:
# mode: auto-fill
# mode: flyspell
# eval: (ispell-change-dictionary "en_US")
# End:
