## Time-stamp: <2017-02-12 13:00:17 vk>
## -*- coding: utf-8; mode: org; -*-
## This file is best viewed with GNU Emacs Org-mode: http://orgmode.org/


* README

This file contains the format templates of your blog.

lazyblorg needs a template file (command line parameter ~--template~)
which holds the output format definitions. It is using (only) the
heading which meets *all* of the following requirements:

- named ~Templates~
- is marked as ~DONE~
- tagged with ~:blog:~
- contains the unique ID property ~lazyblorg-templates~
- contains a ~:LOGBOOK:~ drawer with a time-stamp for being set to a
  ~DONE~ state

(Besides the name ~Templates~ those are the very same criteria for a
blog entry in general, by the way.)

This way, you can switch between different formats by using different
files (using different template files) or different headings within
this file (renaming first level headings and IDs; not recommended),
respectively.

The format templates are located in a heading hierarchy within the
~Templates~ heading. The hierarchy should be self explaining for
you. Please *do not modify headings* since lazyblorg is looking for
their exact form - at least for the first two levels.

Within a heading, each format template is defined in a HTML [[http://orgmode.org/manual/Working-With-Source-Code.html#Working-With-Source-Code][babel
block]].  Its name corresponds to the internal lazyblorg definition. So
please *do not modify the name strings* otherwise lazyblorg gets very
sad!

Within a format template, you will see strings like ~#FOO#~. These
place holder strings will get replaced by your content. If you modify
those, lazyblorg is not able to replace them with your content: *do
not modify/remove/invent place holder strings* by yourself.

In between the format templates, you can write whatever you want
unless it is no babel block of type ~html~: lazyblorg will ignore
these in-between notes.

For documentation about the implemented elements: see
id:implemented-org-elements in [[file:../dev/lazyblorg.org]]

Have fun with modifying lazyblorg to your requirements!

* DONE Templates                                                                  :lb_templates:blog:
:PROPERTIES:
:CREATED:  [2014-12-26 Fri 16:09]
:END:
:LOGBOOK:
- State "DONE"       from "DONE"       [2013-08-21 Wed 17:50]
:END:
:PROPERTIES:
:ID: lazyblorg-templates
:CREATED:  [2013-08-21 Wed 17:50]
:END:

** General elements

*** Sidebar

#+NAME: common-sidebar
#+BEGIN_EXPORT HTML

  <a id="show-sidebar-text" href="#show-sidebar">Show Sidebar</a>
  <div class="sidebar toggle-sidebar">
     <div class="search">
       <iframe id="search-big" src="//duckduckgo.com/search.html?width=140&site=#DOMAIN#&prefill=Search%20blog"></iframe>
       <iframe id="search-narrow" src="//duckduckgo.com/search.html?width=70&k1=-1&k2=s&site=#DOMAIN#&prefill=Search"></iframe>
       <br/>
     </div>
     <ul>
     <li><a href="#BASE-URL#">Recent articles</a></li>
     <li>[[id:#ABOUT-PAGE-ID#][About this blog]]</li>
     <li>[[id:2017-01-03-how-to-use-public-voit][How to use this blog efficiently]]</li>
     <li><a href="#BASE-URL#/feeds/lazyblorg-all.atom_1.0.links-only.xml">Follow/subscribe links</a></li>
     <li><a href="#BASE-URL#/feeds/lazyblorg-all.atom_1.0.links-and-content.xml">Follow/subscribe content</a></li>
     <li><span style="font-size:small"><a href="https://en.wiktionary.org/wiki/TBD">TBD</a>: Per Tag Feeds</span></li>
     <li><span style="font-size:small"><a href="https://en.wiktionary.org/wiki/TBD">TBD</a>: Archive</span></li>
     <li>Top <a href="#BASE-URL#/tags/">tags</a>:</li>
         <ul class="top-tags-list">
              #TOP-TAG-LIST#
         </ul>
     </ul>
  </div>

#+END_EXPORT

*** Sections

- #SECTION-TITLE#: title of the next heading/section
- #SECTION-LEVEL#: relative level of the next heading/section

#+NAME: section-begin
#+BEGIN_EXPORT HTML

	  <header><h#SECTION-LEVEL# class="section-title">#SECTION-TITLE#</h#SECTION-LEVEL#></header>

#+END_EXPORT
*** Paragraph

- #PAR-CONTENT#

#+NAME: paragraph
#+BEGIN_EXPORT HTML

<p>

#PAR-CONTENT#

</p>

#+END_EXPORT

*** Lists

#+NAME: ul-begin
#+BEGIN_EXPORT HTML
	  <ul>
#+END_EXPORT

- #CONTENT#: text of the list item

#+NAME: ul-item
#+BEGIN_EXPORT HTML
	    <li>#CONTENT#</li>
#+END_EXPORT

#+NAME: ul-end
#+BEGIN_EXPORT HTML
	  </ul>
#+END_EXPORT

*** Pre-formatted text

Without name/label:

#+NAME: pre-begin
#+BEGIN_EXPORT HTML

	  <pre>
#+END_EXPORT

#+NAME: pre-end
#+BEGIN_EXPORT HTML
	  </pre>

#+END_EXPORT

With name/label:

#+NAME: named-pre-begin
#+BEGIN_EXPORT HTML

<p>

    #NAME#
	  <pre>
#+END_EXPORT

#+NAME: named-pre-end
#+BEGIN_EXPORT HTML
	  </pre>

</p>
#+END_EXPORT

*** SRC blocks (not HTML)

Without name/label:

#+NAME: src-begin
#+BEGIN_EXPORT HTML

	  <div class="example_code">
	  <pre>
#+END_EXPORT

#+NAME: src-end
#+BEGIN_EXPORT HTML
	  </pre>
    </div>

#+END_EXPORT

With name/label:

#+NAME: named-src-begin
#+BEGIN_EXPORT HTML

<p>

    #NAME#
	  <div class="example_code">
	  <pre>
#+END_EXPORT

#+NAME: named-src-end
#+BEGIN_EXPORT HTML
	  </pre>
    </div>

</p>
#+END_EXPORT

*** HTML blocks

- #NAME#: Org-mode name of the block

#+NAME: html-begin
#+BEGIN_EXPORT HTML

<p>

    #NAME#
	  <div class="example_code">
#+END_EXPORT

#+NAME: html-end
#+BEGIN_EXPORT HTML
	  </div>

</p>

#+END_EXPORT

*** QUOTE blocks

#+NAME: blockquote-begin
#+BEGIN_EXPORT HTML

<blockquote>
#+END_EXPORT

#+NAME: blockquote-end
#+BEGIN_EXPORT HTML
</blockquote>

#+END_EXPORT

*** ignore me

#+NAME:
#+BEGIN_EXPORT HTML
#+END_EXPORT

#+NAME:
#+BEGIN_EXPORT HTML
#+END_EXPORT

** Persistent

*** Entry Page

**** Header

- #BLOGNAME#: short name of the blog
- #COMMON-SIDEBAR# : the sidebar conentent which is shared on all pages
- #ARTICLE-ID#: Org-mode ID property of the blog entry


#+NAME: entrypage-header
#+BEGIN_EXPORT HTML
  <!DOCTYPE html>
  <html xmlns="http://www.w3.org/1999/xhtml">
  <head>
  <meta charset="UTF-8">
  <meta name="author" content="#AUTHOR-NAME#" />
  <meta name="generator" content="lazyblorg" />
  <meta name="orgmode-id" content="#ARTICLE-ID#" />
  <link rel="stylesheet" title="#BLOG-NAME# Standard CSS Style"
        href="#CSS-URL#" type="text/css" media="screen"  />

  <link rel="alternate" type="application/atom+xml" 
        title="#BLOG-NAME# (links only)" href="#FEEDURL_LINKS#" />
  <link rel="alternate" type="application/atom+xml" 
        title="#BLOG-NAME# (links and content)" href="#FEEDURL_CONTENT#" />

  <!-- WARNING: This page is written in HTML5 and might not be displayed correctly in old browsers. -->

  <title>#BLOG-NAME# - Homepage of #AUTHOR-NAME#</title>
  </head>

  <body class="persistent-body">

  <header class="persistent-header">

      <nav class="entrypage-article-header-nav">
        <span class="breadcrumbs">
          <img src="#BLOG-LOGO#" alt="#BLOG-NAME# logo" width="350" style="vertical-align:middle;"><span style="padding-top:1em;">
        </span>
      </nav>

  </header>

  #COMMON-SIDEBAR#

  <div class="entry-page-greetings">
  <p>

    This is the home-page of #AUTHOR-NAME#.

  </p>

  <p>

    On this page you can see the latest blog updates. For further articles, please use the <b>search bar</b> or <b>navigate through <a href="tags/">the blue tags</a></b>.
    My recommendations are <a href="tags/pim/">pim</a>, <a href="tags/privacy/">privacy</a>, or <a href="tags/security/">security</a>.

  </p>

  <p>

    <a href="how-to-use-public-voit/">I recommend</a> any decent <a href="https://en.wikipedia.org/wiki/RSS">RSS</a>/<a href="https://en.wikipedia.org/wiki/Atom_(standard)">Atom aggregator</a> to get notified on blog updates.

  </p>

  <p>

    Most recent articles or updates:

  </p>
  </div>

#+END_EXPORT

**** Article-Preview

- #ARTICLE-TITLE#: heading/title of the blog article
- #ARTICLE-URL#: URL of the blog article
- #ARTICLE-YEAR#: four digit year of the article (folder path)
- #ARTICLE-MONTH#: two digit month of the article (folder path)
- #ARTICLE-DAY#: two digit day of the article (folder path)
- #ARTICLE-PUBLISHED-HTML-DATETIME#: time-stamp of publishing in HTML
  date-time format (e.g., ~2011-10-30T15:00+02:00~)
- #ARTICLE-PUBLISHED-HUMAN-READABLE#: time-stamp of publishing in
  human readable format (e.g., ~2011-10-30T15:00~)
- #ARTICLE-TEASER#: First lines up to the first heading or <hr>-element

#+NAME: article-preview-header
#+BEGIN_EXPORT HTML


<article class="entry-page-article">
#+END_EXPORT

#+NAME: article-preview-tags-begin
#+BEGIN_EXPORT HTML

	  <aside>
	    <ul class="entry-page-article-tags">
#+END_EXPORT

- #TAGNAME#: string of a tag

#+NAME: article-preview-usertag
#+BEGIN_EXPORT HTML
                <li><a class="usertag" href="#BASE-URL#/tags/#TAGNAME#/">#TAGNAME#</a></li>

#+END_EXPORT

As long as lazyblorg does not support tag pages for autotag: use
placeholder article which is defined in this file (below).

#+NAME: article-preview-autotag
#+BEGIN_EXPORT HTML
                <li><a class="autotag" href="#BASE-URL#/2016/11/16/empty-autotag-page/">#TAGNAME#</a></li>

#+END_EXPORT


#+NAME: article-preview-tags-end
#+BEGIN_EXPORT HTML

	    </ul>
	  </aside>
#+END_EXPORT


#+NAME: article-preview-begin
#+BEGIN_EXPORT HTML

<h1><a href="#ARTICLE-URL#">#ARTICLE-YEAR#-#ARTICLE-MONTH#-#ARTICLE-DAY#: #ARTICLE-TITLE#</a></h1>

#ARTICLE-TEASER#

#+END_EXPORT

#+NAME: article-preview-more
#+BEGIN_EXPORT HTML
<p>
<a href="#ARTICLE-URL#" class="article-preview-more">Read the whole article&nbsp;...</a>
</p>
#+END_EXPORT

#+NAME: article-preview-end
#+BEGIN_EXPORT HTML


</article>


#+END_EXPORT

**** Footer

- #BLOGNAME#: short name of the blog

#+NAME: entrypage-footer
#+BEGIN_EXPORT HTML


    <footer>
      <p><i>[[id:#ABOUT-PAGE-ID#][#BLOG-NAME#]]</i> is authored in <a href="//orgmode.org">Org-mode</a> and generated by <a href="https://github.com/novoid/lazyblorg">lazyblorg</a>

	 	&nbsp;&bull;&nbsp; <a href="//validator.w3.org/check/referer">HTML5</a>

	 	&nbsp;&bull;&nbsp; <a href="//jigsaw.w3.org/css-validator/">CSS3</a>
      </p>
    </footer>

  </body>
</html>
#+END_EXPORT


*** Other Persistent Pages

**** Header

- #ARTICLE-TITLE#: heading/title of the blog article
- #ARTICLE-ID#: Org-mode ID property of the blog entry

#+NAME: persistent-header
#+BEGIN_EXPORT HTML
  <!DOCTYPE html>
  <html xmlns="http://www.w3.org/1999/xhtml">
  <head>
  <meta charset="UTF-8">
  <meta name="author" content="#AUTHOR-NAME#" />
  <meta name="generator" content="lazyblorg" />
  <meta name="orgmode-id" content="#ARTICLE-ID#" />
  <link rel="stylesheet" title="#BLOG-NAME# Standard CSS Style"
        href="#CSS-URL#" type="text/css" media="screen"  />

  <link rel="alternate" type="application/atom+xml" 
        title="#BLOG-NAME# (links only)" href="#FEEDURL_LINKS#" />
  <link rel="alternate" type="application/atom+xml" 
        title="#BLOG-NAME# (links and content)" href="#FEEDURL_CONTENT#" />

  <!-- WARNING: This page is written in HTML5 and might not be displayed correctly in old browsers. -->

      <title>#ARTICLE-TITLE#</title>

  </head>

#+END_EXPORT

**** Top of Article

- #BLOGNAME#: short name of the blog
- #ARTICLE-YEAR#: four digit year of the article (folder path)
- #ARTICLE-MONTH#: two digit month of the article (folder path)
- #ARTICLE-DAY#: two digit day of the article (folder path)
- #ARTICLE-PUBLISHED-HTML-DATETIME#: time-stamp of publishing in HTML
  date-time format (e.g., 2011-10-30T15:00+02:00)
- #ARTICLE-PUBLISHED-HUMAN-READABLE#: time-stamp of publishing in
  human readable format (e.g., 2011-10-30T15:00)
- #COMMON-SIDEBAR# : the sidebar conentent which is shared on all pages

#+NAME: persistent-header-begin
#+BEGIN_EXPORT HTML
  <body>

    <div class="common-orgsource"><a href="source.org.txt">&#960;</a></div>

	<header>

	  <nav class="persistent-article-header-nav">
	    <span class="breadcrumbs">
	      <a href="../"><img src="#BLOG-LOGO#" alt="#BLOG-NAME# logo" width="350" style="vertical-align:middle;"></a>
	    </span>
	  </nav>

#+END_EXPORT

#+NAME: persistent-header-end
#+BEGIN_EXPORT HTML

	  <h1 class="common-article-header-title">#ARTICLE-TITLE#</h1>

	</header>

    #COMMON-SIDEBAR#

    <article class="common-article">

#+END_EXPORT

#+NAME: persistent-end
#+BEGIN_EXPORT HTML

    </article>

#+END_EXPORT

**** Footer

#+NAME: persistent-footer
#+BEGIN_EXPORT HTML
	  <aside class="published-on">
	    Published on <time datetime="#ARTICLE-PUBLISHED-HTML-DATETIME#">#ARTICLE-PUBLISHED-HUMAN-READABLE#</time>
	  </aside>

   <p class="email-comment">
      <a href="mailto:#COMMENT-EMAIL-ADDRESS#?subject=#ARTICLE-ID#%20comment:%20&body=Please%20do%20not%20remove%20'#ARTICLE-ID#%20comment:'%20in%20subject%20and%20please%20tell%20me%20whether%20or%20not%20it%20is%20OK%20to%20add%20your%20comment%20and%2For%20your%20email%20address%20to%20the%20blog%20entry!">Comment via email</a> or via <a href="//disqus.com">Disqus</a> comments below:
   </p>

    <div id="disqus_thread"></div>
    <div id="disqus_loader" style="text-align: center">
      <!-- stolen from http://blog.yjl.im/2012/04/let-your-readers-decide-when-to-load.html -->
      <button onclick="load_disqus()">Load Disqus Comments</button>
      <script>
        function load_disqus()
        {
          var dsq = document.createElement('script');
          dsq.type = 'text/javascript';
          dsq.async = true;
          dsq.src = "//#DISQUS-NAME#.disqus.com/embed.js";
          var disqus_identifier = '#ARTICLE-ID#';
          (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
          var ldr = document.getElementById('disqus_loader');
          ldr.parentNode.removeChild(ldr);
        }
      </script>
    </div>
    <noscript>Please enable JavaScript to view the <a href="//disqus.com/?ref_noscript">Disqus comments.</a></noscript>

    <footer>
      <p><i>[[id:#ABOUT-PAGE-ID#][#BLOG-NAME#]]</i> is authored in <a href="//orgmode.org">Org-mode</a> and generated by <a href="https://github.com/novoid/lazyblorg">lazyblorg</a>

	 	&nbsp;&bull;&nbsp; <a href="//validator.w3.org/check/referer">HTML5</a>

	 	&nbsp;&bull;&nbsp; <a href="//jigsaw.w3.org/css-validator/">CSS3</a>
      </p>
    </footer>

  </body>
</html>
#+END_EXPORT

** Article

*** Header

- #ARTICLE-TITLE#: heading/title of the blog article
- #ARTICLE-ID#: Org-mode ID property of the blog entry

#+NAME: article-header
#+BEGIN_EXPORT HTML
  <!DOCTYPE html>
  <html xmlns="http://www.w3.org/1999/xhtml">
  <head>
  <meta charset="UTF-8">

  <meta name="author" content="#AUTHOR-NAME#" />
  <meta name="generator" content="lazyblorg" />
  <meta name="description" content="#ARTICLE-TITLE#" />
  <meta name="orgmode-id" content="#ARTICLE-ID#" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:site" content="@#TWITTER-HANDLE#" />
  <meta name="twitter:creator" content="@#TWITTER-HANDLE#" />
  <meta name="twitter:title" content="#BLOG-NAME#" />
  <meta name="twitter:description" content="#ARTICLE-TITLE#" />
  <meta name="twitter:image" content="#TWITTER-IMAGE#" />

  <meta property="og:type" content="article" />
  <meta property="og:title" content="#BLOG-NAME#" />
  <meta property="og:description" content="#ARTICLE-TITLE#" />
  <meta property="og:image" content="#TWITTER-IMAGE#" />
  <meta property="og:site_name" content="#BLOG-NAME# - Web-page of #AUTHOR-NAME#">
  <meta property="article:published_time" content="#ARTICLE-PUBLISHED-HTML-DATETIME#" />
  <meta property="article:author" content="#AUTHOR-NAME#" />

  <link rel="stylesheet" title="#BLOG-NAME# Standard CSS Style"
        href="#CSS-URL#" type="text/css" media="screen"  />

  <link rel="alternate" type="application/atom+xml" 
        title="#BLOG-NAME# (links only)" href="#FEEDURL_LINKS#" />
  <link rel="alternate" type="application/atom+xml" 
        title="#BLOG-NAME# (links and content)" href="#FEEDURL_CONTENT#" />

  <!-- WARNING: This page is written in HTML5 and might not be displayed correctly in old browsers. -->

      <!-- link rel="stylesheet" type="text/css" href="../../../../style.css" / -->
      <title>#ARTICLE-TITLE#</title>

  </head>
#+END_EXPORT

*** Top of Article

- #BLOGNAME#: short name of the blog
- #ARTICLE-YEAR#: four digit year of the article (folder path)
- #ARTICLE-MONTH#: two digit month of the article (folder path)
- #ARTICLE-DAY#: two digit day of the article (folder path)
- #ARTICLE-PUBLISHED-HTML-DATETIME#: time-stamp of publishing in HTML
  date-time format (e.g., 2011-10-30T15:00+02:00)
- #ARTICLE-PUBLISHED-HUMAN-READABLE#: time-stamp of publishing in
  human readable format (e.g., 2011-10-30T15:00)
- #COMMON-SIDEBAR# : the sidebar conentent which is shared on all pages

#+NAME: article-header-begin
#+BEGIN_EXPORT HTML
  <body>

    <div class="common-orgsource"><a href="source.org.txt">&#960;</a></div>


	<header>

	  <nav class="temporal-article-header-nav">
	    <span class="breadcrumbs">
	      <a href="../../../../"><img src="#BLOG-LOGO#" alt="#BLOG-NAME# logo" width="350" style="vertical-align:middle;"></a><span style="padding-top:1em;">&nbsp;&nbsp;&nbsp;&nbsp;&raquo;
	      #ARTICLE-YEAR#&nbsp;&ndash;&nbsp;#ARTICLE-MONTH#&nbsp;&ndash;&nbsp;#ARTICLE-DAY#</span>
	      <!-- a href="../../../">#ARTICLE-YEAR#</a>&nbsp;&ndash;&nbsp;<a href="../../">#ARTICLE-MONTH#</a>&nbsp;&ndash;&nbsp;<a href="../">#ARTICLE-DAY#</a -->
	    </span>
	  </nav>

#+END_EXPORT


#+NAME: article-tags-begin
#+BEGIN_EXPORT HTML
	  <aside class="common-tags">
	    <ul>

#+END_EXPORT

- #TAGNAME#: string of a tag

#+NAME: article-usertag
#+BEGIN_EXPORT HTML
                <li><a class="usertag" href="#BASE-URL#/tags/#TAGNAME#/">#TAGNAME#</a></li>

#+END_EXPORT

#+NAME: article-autotag
#+BEGIN_EXPORT HTML
                <li><a class="autotag" href="#BASE-URL#/tags/#TAGNAME#/">#TAGNAME#</a></li>

#+END_EXPORT

#+NAME: article-tags-end
#+BEGIN_EXPORT HTML
	    </ul>
	  </aside>

#+END_EXPORT



#+NAME: article-header-end
#+BEGIN_EXPORT HTML

	  <h1 class="common-article-header-title">#ARTICLE-TITLE#</h1>

	</header>

  #COMMON-SIDEBAR#

  <article class="common-article">

#+END_EXPORT

#+NAME: article-end
#+BEGIN_EXPORT HTML


  </article>

#+END_EXPORT

*** Footer

#+NAME: article-footer
#+BEGIN_EXPORT HTML
	  <aside class="published-on">
	    Published on <time datetime="#ARTICLE-PUBLISHED-HTML-DATETIME#">#ARTICLE-PUBLISHED-HUMAN-READABLE#</time>
	  </aside>

   <p class="email-comment">
      <a href="mailto:#COMMENT-EMAIL-ADDRESS#?subject=#ARTICLE-ID#%20comment:%20&body=Please%20do%20not%20remove%20'#ARTICLE-ID#%20comment:'%20in%20subject%20and%20please%20tell%20me%20whether%20or%20not%20it%20is%20OK%20to%20add%20your%20comment%20and%2For%20your%20email%20address%20to%20the%20blog%20entry!">Comment via email</a> or via <a href="//disqus.com">Disqus</a> comments below:
   </p>

    <div id="disqus_thread"></div>
    <div id="disqus_loader" style="text-align: center">
      <!-- stolen from http://blog.yjl.im/2012/04/let-your-readers-decide-when-to-load.html -->
      <button onclick="load_disqus()">Load Disqus Comments</button>
      <script>
        function load_disqus()
        {
          var dsq = document.createElement('script');
          dsq.type = 'text/javascript';
          dsq.async = true;
          dsq.src = "//#DISQUS-NAME#.disqus.com/embed.js";
          var disqus_identifier = '#ARTICLE-ID#';
          (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
          var ldr = document.getElementById('disqus_loader');
          ldr.parentNode.removeChild(ldr);
        }
      </script>
    </div>
    <noscript>Please enable JavaScript to view the <a href="//disqus.com/?ref_noscript">Disqus comments.</a></noscript>

    <footer>
      <p><i>[[id:#ABOUT-PAGE-ID#][#BLOG-NAME#]]</i> is authored in <a href="//orgmode.org">Org-mode</a> and generated by <a href="https://github.com/novoid/lazyblorg">lazyblorg</a>

	 	&nbsp;&bull;&nbsp; <a href="//validator.w3.org/check/referer">HTML5</a>

	 	&nbsp;&bull;&nbsp; <a href="//jigsaw.w3.org/css-validator/">CSS3</a>
      </p>
    </footer>

  </body>
</html>
#+END_EXPORT

** Tag Overview Page

A single page which is used as template for =example.com/tags/index.html=.

*** Header

- #ARTICLE-TITLE#: heading/title of the blog article
- #ARTICLE-ID#: Org-mode ID property of the blog entry

#+NAME: tagoverviewpage-header
#+BEGIN_EXPORT HTML
  <!DOCTYPE html>
  <html xmlns="http://www.w3.org/1999/xhtml">
  <head>
  <meta charset="UTF-8">

  <meta name="author" content="#AUTHOR-NAME#" />
  <meta name="generator" content="lazyblorg" />
  <meta name="description" content="Tag overview page" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:site" content="@#TWITTER-HANDLE#" />
  <meta name="twitter:creator" content="@#TWITTER-HANDLE#" />
  <meta name="twitter:title" content="#BLOG-NAME#" />
  <meta name="twitter:description" content="Tag overview page" />
  <meta name="twitter:image" content="#TWITTER-IMAGE#" />

  <meta property="og:type" content="article" />
  <meta property="og:title" content="#BLOG-NAME#" />
  <meta property="og:description" content="Tag overview page" />
  <meta property="og:image" content="#TWITTER-IMAGE#" />
  <meta property="og:site_name" content="#BLOG-NAME# - Web-page of #AUTHOR-NAME#">
  <meta property="article:published_time" content="#ARTICLE-PUBLISHED-HTML-DATETIME#" />
  <meta property="article:author" content="#AUTHOR-NAME#" />

  <link rel="stylesheet" title="#BLOG-NAME# Standard CSS Style"
        href="#CSS-URL#" type="text/css" media="screen"  />

  <link rel="alternate" type="application/atom+xml" 
        title="#BLOG-NAME# (links only)" href="#FEEDURL_LINKS#" />
  <link rel="alternate" type="application/atom+xml" 
        title="#BLOG-NAME# (links and content)" href="#FEEDURL_CONTENT#" />

  <!-- WARNING: This page is written in HTML5 and might not be displayed correctly in old browsers. -->

      <title>Tags of #BLOG-NAME#</title>

  </head>
#+END_EXPORT

*** Article Body

#+NAME: tagoverviewpage-body
#+BEGIN_EXPORT HTML
  <body>

	<header>

	  <nav class="temporal-article-header-nav">
	    <span class="breadcrumbs">
	      <a href="../"><img src="#BLOG-LOGO#" alt="#BLOG-NAME# logo" width="350" style="vertical-align:middle;"></a><span style="padding-top:1em;">&nbsp;&nbsp;&nbsp;&nbsp;&raquo;Tags</span>
	    </span>
	  </nav>

	</header>

  #COMMON-SIDEBAR#

  <article class="common-article">

    <p>

    Tag cloud of all tags except «<a href="hardware">hardware</a>» and «<a href="software">software</a>» which are my most general tags.
    The bigger the tag, the more articles are tagged with it.
    <!-- Tag Cloud: FIXXME: legend explaining size and colour -->

    </p>

	  <aside class="tag-cloud">
	    <ul>

#TAGOVERVIEW-CLOUD#

            </ul>
          </aside>

  </article>

#+END_EXPORT

*** Footer

#+NAME: tagoverviewpage-footer
#+BEGIN_EXPORT HTML
    <footer>
      <p><i>[[id:#ABOUT-PAGE-ID#][#BLOG-NAME#]]</i> is authored in <a href="//orgmode.org">Org-mode</a> and generated by <a href="https://github.com/novoid/lazyblorg">lazyblorg</a>

	 	&nbsp;&bull;&nbsp; <a href="//validator.w3.org/check/referer">HTML5</a>

	 	&nbsp;&bull;&nbsp; <a href="//jigsaw.w3.org/css-validator/">CSS3</a>
      </p>
    </footer>

  </body>
</html>
#+END_EXPORT

** Tag Pages

Pages that describe a tag. Corresponding Org-mode entries must have:
- heading is a single word: the tag itself
- tags =blog= and =lb_tag= set
- =ID= set in properties
- marked as =DONE=

*** Header

- #ARTICLE-TITLE#: heading/title of the blog article
- #ARTICLE-ID#: Org-mode ID property of the blog entry

#+NAME: tagpage-header
#+BEGIN_EXPORT HTML
  <!DOCTYPE html>
  <html xmlns="http://www.w3.org/1999/xhtml">
  <head>
  <meta charset="UTF-8">

  <meta name="author" content="#AUTHOR-NAME#" />
  <meta name="generator" content="lazyblorg" />
  <meta name="description" content="Tag page for tag #ARTICLE-TITLE#" />
  <meta name="orgmode-id" content="#ARTICLE-ID#" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:site" content="@#TWITTER-HANDLE#" />
  <meta name="twitter:creator" content="@#TWITTER-HANDLE#" />
  <meta name="twitter:title" content="#BLOG-NAME#" />
  <meta name="twitter:description" content="Tag page for tag #ARTICLE-TITLE#" />
  <meta name="twitter:image" content="#TWITTER-IMAGE#" />

  <meta property="og:type" content="article" />
  <meta property="og:title" content="#BLOG-NAME#" />
  <meta property="og:description" content="Tag page for tag #ARTICLE-TITLE#" />
  <meta property="og:image" content="#TWITTER-IMAGE#" />
  <meta property="og:site_name" content="#BLOG-NAME# - Web-page of #AUTHOR-NAME#">
  <meta property="article:published_time" content="#ARTICLE-PUBLISHED-HTML-DATETIME#" />
  <meta property="article:author" content="#AUTHOR-NAME#" />

  <link rel="stylesheet" title="#BLOG-NAME# Standard CSS Style"
        href="#CSS-URL#" type="text/css" media="screen"  />

  <link rel="alternate" type="application/atom+xml" 
        title="#BLOG-NAME# (links only)" href="#FEEDURL_LINKS#" />
  <link rel="alternate" type="application/atom+xml" 
        title="#BLOG-NAME# (links and content)" href="#FEEDURL_CONTENT#" />

  <!-- WARNING: This page is written in HTML5 and might not be displayed correctly in old browsers. -->

      <!-- link rel="stylesheet" type="text/css" href="../../../../style.css" / -->
      <title>The Tag &laquo;#ARTICLE-TITLE#&raquo;</title>

  </head>
#+END_EXPORT

*** Top of Article

- #BLOGNAME#: short name of the blog
- #ARTICLE-YEAR#: four digit year of the article (folder path)
- #ARTICLE-MONTH#: two digit month of the article (folder path)
- #ARTICLE-DAY#: two digit day of the article (folder path)
- #ARTICLE-PUBLISHED-HTML-DATETIME#: time-stamp of publishing in HTML
  date-time format (e.g., 2011-10-30T15:00+02:00)
- #ARTICLE-PUBLISHED-HUMAN-READABLE#: time-stamp of publishing in
  human readable format (e.g., 2011-10-30T15:00)
- #COMMON-SIDEBAR# : the sidebar conentent which is shared on all pages

#+NAME: tagpage-header-begin
#+BEGIN_EXPORT HTML
  <body>

    <div class="common-orgsource"><a href="source.org.txt">&#960;</a></div>


	<header>

	  <nav class="temporal-article-header-nav">
	    <span class="breadcrumbs">
	      <a href="../../../../"><img src="#BLOG-LOGO#" alt="#BLOG-NAME# logo" width="350" style="vertical-align:middle;"></a><span style="padding-top:1em;">&nbsp;&nbsp;&nbsp;&nbsp;&raquo;<a href="../">Tags</a>&nbsp;&nbsp;&nbsp;&nbsp;&raquo;#ARTICLE-TITLE#</span>
	    </span>
	  </nav>

#+END_EXPORT


#+NAME: tagpage-tags-begin
#+BEGIN_EXPORT HTML
	  <aside class="common-tags">
	    <ul>

#+END_EXPORT

- #TAGNAME#: string of a tag

#+NAME: tagpage-usertag
#+BEGIN_EXPORT HTML
                <li><a class="usertag" href="#BASE-URL#/tags/#TAGNAME#/">#ARTICLE_TITLE#</a></li>

#+END_EXPORT

#+NAME: tagpage-autotag
#+BEGIN_EXPORT HTML
                <li><a class="autotag" href="#BASE-URL#/tags/#TAGNAME#/">#TAGNAME#</a></li>

#+END_EXPORT

#+NAME: tagpage-tags-end
#+BEGIN_EXPORT HTML
	    </ul>
	  </aside>

#+END_EXPORT

#+NAME: tagpage-header-end
#+BEGIN_EXPORT HTML

	  <h1 class="common-article-header-title">Tag Page for the Tag "#ARTICLE-TITLE#"</h1>

	</header>

  #COMMON-SIDEBAR#

  <article class="common-article">

#+END_EXPORT

#+NAME: tagpage-end
#+BEGIN_EXPORT HTML

  <hr />

  <p>
  All articles tagged with #ARTICLE-TITLE# <span class="minor-contrast">(sorted by last update, oldest on top)</span>:
  </p>

  <p>
  #TAG-PAGE-LIST#
  </p>

  </article>

#+END_EXPORT

*** Footer

I'm re-using article-footer.

** Day Overview

FIXXME

** Month Overview

*** Header

- #BLOGNAME#: short name of the blog
- #YEAR#: four digit year
- #MONTH-LONGNAME#: name of the month like "January" or "February"
- #MONTH-SHORTNAME#: three letter name of the month like "Jan" or "Feb"
- #MONTH-TWODIGITNUMBER#: number of the month like "01" or "02"

#+NAME: month-header
#+BEGIN_EXPORT HTML
  <!DOCTYPE html>
  <html xmlns="http://www.w3.org/1999/xhtml">
  <head>
  <meta charset="UTF-8">
  <meta name="author" content="#AUTHOR-NAME#" />
  <meta name="generator" content="lazyblorg" />
  <link rel="stylesheet" title="#BLOG-NAME# Standard CSS Style"
        href="#CSS-URL#" type="text/css" media="screen"  />

  <link rel="alternate" type="application/atom+xml" 
        title="#BLOG-NAME# (links only)" href="#FEEDURL_LINKS#" />
  <link rel="alternate" type="application/atom+xml" 
        title="#BLOG-NAME# (links and content)" href="#FEEDURL_CONTENT#" />

  <!-- WARNING: This page is written in HTML5 and might not be displayed correctly in old browsers. -->

  <title>#BLOGNAME#: #YEAR#-#MONTH-TWODIGITNUMBER#</title>
  </head>

  <body>

  <article class="month-overview">

	<header>

	  <nav class="month-overview-header-nav">
	    <span class="breadcrumbs">
	      <a href="../../"><img src="#BLOG-LOGO#" alt="#BLOG-NAME# logo" width="350" style="vertical-align:middle;"></a><span style="padding-top:1em;">&nbsp;&nbsp;&nbsp;&nbsp;&raquo;
	      #YEAR#&nbsp;&ndash;&nbsp;#MONTH-TWODIGITNUMBER#</span>
	    </span>
	  </nav>

	  <h1 class="article-title">#YEAR#-#MONTH-TWODIGITNUMBER#</h1>

	</header>

  <p><ul class="month-body">

#+END_EXPORT

*** Article-Link

- #ARTICLE-TITLE#: heading/title of the blog article
- #ARTICLE-URL#: URL of the blog article
- #ARTICLE-YEAR#: four digit year of the article (folder path)
- #ARTICLE-MONTH#: two digit month of the article (folder path)
- #ARTICLE-DAY#: two digit day of the article (folder path)
- #ARTICLE-PUBLISHED-HTML-DATETIME#: time-stamp of publishing in HTML
  date-time format (e.g., 2011-10-30T15:00+02:00)
- #ARTICLE-PUBLISHED-HUMAN-READABLE#: time-stamp of publishing in
  human readable format (e.g., 2011-10-30T15:00)

#+NAME: article-list-link
#+BEGIN_EXPORT HTML
<li><a href="#ARTICLE-URL#">#ARTICLE-YEAR#-#ARTICLE-MONTH#-#ARTICLE-DAY#: #ARTICLE-TITLE#</a></li>
#+END_EXPORT

*** Footer

- #BLOGNAME#: short name of the blog
- #YEAR#: four digit year
- #MONTH-LONGNAME#: name of the month like "January" or "February"
- #MONTH-SHORTNAME#: three letter name of the month like "Jan" or "Feb"
- #MONTH-TWODIGITNUMBER#: number of the month like "01" or "02"

#+NAME: month-footer
#+BEGIN_EXPORT HTML

    </ul></p>
    </article>

    <footer>
      <p><i>[[id:#ABOUT-PAGE-ID#][#BLOG-NAME#]]</i> is authored in <a href="//orgmode.org">Org-mode</a> and generated by <a href="https://github.com/novoid/lazyblorg">lazyblorg</a>

	 	&nbsp;&bull;&nbsp; <a href="//validator.w3.org/check/referer">HTML5</a>

	 	&nbsp;&bull;&nbsp; <a href="//jigsaw.w3.org/css-validator/">CSS3</a>
      </p>
    </footer>

  </body>
</html>
#+END_EXPORT

** Year Overview
:PROPERTIES:
:CREATED:  [2016-11-16 Wed 21:33]
:END:

FIXXME


* DONE Empty Autotag Page                                                               :blog:hidden:
CLOSED: [2016-11-16 Wed 21:39]
:PROPERTIES:
:ID: empty-autotag-page
:CREATED:  [2016-11-16 Wed 21:33]
:END:
:LOGBOOK:
- State "DONE"       from "NEXT"       [2016-11-16 Wed 21:39]
:END:

** English

This is a placeholder blog article which is used for autotag pages.

As long as lazyblorg does not support tag pages for autotags, every
autotag links to here.

Autotags are tags like 'language:english' or 'size:small' and so on.

** Deutsch

Das ist eine Platzhalterseite, die als Sprungziel verwendet wird, bis
lazyblorg auch tag pages für autotags unterstützt.

Autotags sind tags wie beispielsweise 'language:english' oder
'size:small' und so weiter.

* Local Variables                                                                          :noexport:
:PROPERTIES:
:CREATED:  [2014-12-26 Fri 16:09]
:END:
# Local Variables:
# mode: auto-fill
# mode: flyspell
# eval: (ispell-change-dictionary "en_US")
# End:
