## Time-stamp: <2014-03-01 19:36:31 vk>
## -*- coding: utf-8; mode: org; -*-
## This file is best viewed with GNU Emacs Org-mode: http://orgmode.org/


* README

This file contains the format templates of your blog.

lazyblorg needs a template file (command line parameter ~--template~)
which holds the output format definitions. It is using (only) the
heading which meets *all* of the following requirements:

- named ~Templates~
- is marked as ~DONE~
- tagged with ~:blog:~
- contains the unique ID property ~lazyblorg-templates~
- contains a ~:LOGBOOK:~ drawer with a time-stamp for being set to a
  ~DONE~ state

(Besides the name ~Templates~ those are the very same criteria for a
blog entry in general, by the way.)

This way, you can switch between different formats by using different
files (using different template files) or different headings within
this file (renaming first level headings and IDs; not recommended),
respectively.

The format templates are located in a heading hierarchy within the
~Templates~ heading. The hierarchy should be self explaining for
you. Please *do not modify headings* since lazyblorg is looking for
their exact form - at least for the first two levels.

Within a heading, each format template is defined in a HTML [[http://orgmode.org/manual/Working-With-Source-Code.html#Working-With-Source-Code][babel
block]].  Its name corresponds to the internal lazyblorg definition. So
please *do not modify the name strings* otherwise lazyblorg gets very
sad!

Within a format template, you will see strings like ~#FOO#~. These
place holder strings will get replaced by your content. If you modify
those, lazyblorg is not able to replace them with your content: *do
not modify/remove/invent place holder strings* by yourself.

In between the format templates, you can write whatever you want
unless it is no babel block of type ~html~: lazyblorg will ignore
these in-between notes.

For documentation about the implemented elements: see
id:implemented-org-elements in [[file:../dev/lazyblorg.org]]

Have fun with modifying lazyblorg to your requirements!

* DONE Templates                                           :lb_templates:blog:
:LOGBOOK:
- State "DONE"       from "DONE"       [2013-08-21 Wed 17:50]
:END:
:PROPERTIES:
:ID: lazyblorg-templates
:CREATED:  [2013-08-21 Wed 17:50]
:END:

** Article

*** Header

- #ARTICLE-TITLE#: heading/title of the blog article

#+NAME: article-header
#+BEGIN_HTML
  <!DOCTYPE html>
  <html xmlns="http://www.w3.org/1999/xhtml">
  <meta charset="UTF-8">
  <meta name="author" content="Karl Voit" />
  <meta name="generator" content="lazyblorg" />
  <link rel="stylesheet" title="public voit Standard CSS Style"
        href="http://Karl-Voit.at/public_voit.css" type="text/css" media="screen"  />

  <!-- WARNING: This page is written in (X)HTML5 and might not be displayed correctly in old browsers. -->

    <head>
      <!-- link rel="stylesheet" type="text/css" href="../../../../style.css" / -->
      <title>#ARTICLE-TITLE#</title>
      
    </head>
#+END_HTML

*** Footer

- #ABOUT-BLOG#: a line of text which describes the blog in general

#+NAME: article-footer
#+BEGIN_HTML
	  <aside class="published-on">
	    Published on <time datetime="#ARTICLE-PUBLISHED-HTML-DATETIME#">#ARTICLE-PUBLISHED-HUMAN-READABLE#</time>
	  </aside>

   <p class="email-comment">
      Comment via <a href="mailto:publicvoit-comment@Karl-Voit.at?subject=#ARTICLE-ID# comment: &body=Please do not remove '#ARTICLE-ID# comment:' in subject and please tell me whether or not it is OK to add your comment and/or your email address to the blog entry!">publicvoit-comment@Karl-Voit.at</a>
   </p>

    <footer>
      <p><i>#ABOUT-BLOG#</i> is authored in <a href="http://orgmode.org">Org-mode</a> and generated by <a href="https://github.com/novoid/lazyblorg">lazyblorg</a>

	 	&nbsp;&bull;&nbsp; <a href="http://validator.w3.org/check/referer">HTML5</a>

	 	&nbsp;&bull;&nbsp; <a href="http://jigsaw.w3.org/css-validator/">CSS3</a>
      </p>
    </footer>

  </body>
</html>
#+END_HTML

*** Top of Article

- #BLOGNAME#: short name of the blog
- #ARTICLE-YEAR#: four digit year of the article (folder path)
- #ARTICLE-MONTH#: two digit month of the article (folder path)
- #ARTICLE-DAY#: two digit day of the article (folder path)
- #ARTICLE-PUBLISHED-HTML-DATETIME#: time-stamp of publishing in HTML
  date-time format (e.g., 2011-10-30T15:00+02:00)
- #ARTICLE-PUBLISHED-HUMAN-READABLE#: time-stamp of publishing in
  human readable format (e.g., 2011-10-30T15:00)

#+NAME: article-header-begin
#+BEGIN_HTML
  <body>

    <div class="article-orgsource"><a href="source.org.txt">&#960;</a></div>

    <article class="article">


	<header>

	  <nav class="article-header-nav">
	    <span class="breadcrumbs">
	      <a href="../../../../"><img src="http://karl-voit.at/images/public-voit_logo.svg" alt="public voit logo" width="350" style="vertical-align:middle;"></a><span style="padding-top:1em;">&nbsp;&nbsp;&nbsp;&nbsp;&raquo;
	      #ARTICLE-YEAR#&nbsp;&ndash;&nbsp;#ARTICLE-MONTH#&nbsp;&ndash;&nbsp;#ARTICLE-DAY#</span>
	      <!-- a href="../../../">#ARTICLE-YEAR#</a>&nbsp;&ndash;&nbsp;<a href="../../">#ARTICLE-MONTH#</a>&nbsp;&ndash;&nbsp;<a href="../">#ARTICLE-DAY#</a -->
	    </span>
	  </nav>

#+END_HTML


#+NAME: article-tags-begin
#+BEGIN_HTML
	  <aside>
	    <ul class="tags">
#+END_HTML

- #TAGNAME#: string of a tag

#+NAME: article-tag
#+BEGIN_HTML
	      <!-- span class="tag">#TAGNAME#</span>&nbsp;-->
        <li><a href="#">#TAGNAME#</a></li>
#+END_HTML

#+NAME: article-tags-end
#+BEGIN_HTML
	    </ul>
	  </aside>
#+END_HTML

#+NAME: article-header-end
#+BEGIN_HTML

	  <h1 class="article-title">#ARTICLE-TITLE#</h1>

	</header>

  <div class="article-body">

#+END_HTML

#+NAME: article-end
#+BEGIN_HTML

    </div> <!-- article-body -->
    </article>

#+END_HTML

*** Sections

- #SECTION-TITLE#: title of the next heading/section
- #SECTION-LEVEL#: relative level of the next heading/section

#+NAME: section-begin
#+BEGIN_HTML

	  <header><h#SECTION-LEVEL# class="section-title">#SECTION-TITLE#</h#SECTION-LEVEL#></header>

#+END_HTML

*** Paragraph

- #PAR-CONTENT#

#+NAME: paragraph
#+BEGIN_HTML

<p>

#PAR-CONTENT#

</p>

#+END_HTML

*** URLs (please ignore)

*NOTE*: this does not have any influence on URLs and might be removed
in future.

- #A-URL#: URL of a hyperlink
- #CONTENT#: description of the hyperlink

#+NAME: a-href
#+BEGIN_HTML
<a href="#A-URL#">#CONTENT#</a>
#+END_HTML

*** Lists

#+NAME: ul-begin
#+BEGIN_HTML
	  <ul>
#+END_HTML

- #CONTENT#: text of the list item

#+NAME: ul-item
#+BEGIN_HTML
	    <li>#CONTENT#</li>
#+END_HTML

#+NAME: ul-end
#+BEGIN_HTML
	  </ul>
#+END_HTML

*** Pre-formatted text

Without name/label:

#+NAME: pre-begin
#+BEGIN_HTML

	  <pre>
#+END_HTML

#+NAME: pre-end
#+BEGIN_HTML
	  </pre>

#+END_HTML

With name/label:

#+NAME: named-pre-begin
#+BEGIN_HTML

<p>

    #NAME#:<br />
	  <pre>
#+END_HTML

#+NAME: named-pre-end
#+BEGIN_HTML
	  </pre>

</p>
#+END_HTML

*** HTML blocks

- #NAME#: Org-mode name of the block

#+NAME: html-begin
#+BEGIN_HTML

<p>

    #NAME#:<br />
	  <div class="example_code">
#+END_HTML

#+NAME: html-end
#+BEGIN_HTML
	  </div>

</p>

#+END_HTML

*** QUOTE blocks

#+NAME: blockquote-begin
#+BEGIN_HTML

<blockquote>
#+END_HTML

#+NAME: blockquote-end
#+BEGIN_HTML
</blockquote>

#+END_HTML

*** ignore me

#+NAME:
#+BEGIN_HTML
#+END_HTML

#+NAME:
#+BEGIN_HTML
#+END_HTML




** Day Overview

FIXXME

** Month Overview

*** Header

- #BLOGNAME#: short name of the blog
- #YEAR#: four digit year
- #MONTH-LONGNAME#: name of the month like "Jannuary" or "February"
- #MONTH-SHORTNAME#: three letter name of the month like "Jan" or "Feb"
- #MONTH-TWODIGITNUMBER#: number of the month like "01" or "02"

#+NAME: month-header
#+BEGIN_HTML
  <!DOCTYPE html>
  <html xmlns="http://www.w3.org/1999/xhtml">
  <meta charset="UTF-8">
  <meta name="author" content="Karl Voit" />
  <meta name="generator" content="lazyblorg" />
  <link rel="stylesheet" title="public voit Standard CSS Style"
        href="http://Karl-Voit.at/public_voit.css" type="text/css" media="screen"  />

  <!-- WARNING: This page is written in (X)HTML5 and might not be displayed correctly in old browsers. -->

    <head>
      <title>#BLOGNAME#: #YEAR#-#MONTH-TWODIGITNUMBER#</title>
    </head>

  <body>

  <article class="month-overview">

	<header>

	  <nav class="article-header-nav">
	    <span class="breadcrumbs">
	      <a href="../../"><img src="http://karl-voit.at/images/public-voit_logo.svg" alt="public voit logo" width="350" style="vertical-align:middle;"></a><span style="padding-top:1em;">&nbsp;&nbsp;&nbsp;&nbsp;&raquo;
	      #YEAR#&nbsp;&ndash;&nbsp;#MONTH-TWODIGITNUMBER#</span>
	    </span>
	  </nav>

	  <h1 class="article-title">#YEAR#-#MONTH-TWODIGITNUMBER#</h1>

	</header>

  <p><ul class="month-body">

#+END_HTML

*** Article-Link

- #ARTICLE-TITLE#: heading/title of the blog article
- #ARTICLE-URL#: URL of the blog article
- #ARTICLE-YEAR#: four digit year of the article (folder path)
- #ARTICLE-MONTH#: two digit month of the article (folder path)
- #ARTICLE-DAY#: two digit day of the article (folder path)
- #ARTICLE-PUBLISHED-HTML-DATETIME#: time-stamp of publishing in HTML
  date-time format (e.g., 2011-10-30T15:00+02:00)
- #ARTICLE-PUBLISHED-HUMAN-READABLE#: time-stamp of publishing in
  human readable format (e.g., 2011-10-30T15:00)

#+NAME: article-list-link
#+BEGIN_HTML
<li><a href="#ARTICLE-URL#">#ARTICLE-YEAR#-#ARTICLE-MONTH#-#ARTICLE-DAY#: #ARTICLE-TITLE#</a></li>
#+END_HTML

*** Footer

- #BLOGNAME#: short name of the blog
- #YEAR#: four digit year
- #MONTH-LONGNAME#: name of the month like "Jannuary" or "February"
- #MONTH-SHORTNAME#: three letter name of the month like "Jan" or "Feb"
- #MONTH-TWODIGITNUMBER#: number of the month like "01" or "02"

#+NAME: month-footer
#+BEGIN_HTML

    </ul></p>
    </article>

    <footer>
      <p><i>#ABOUT-BLOG#</i> is authored in <a href="http://orgmode.org">Org-mode</a> and generated by <a href="https://github.com/novoid/lazyblorg">lazyblorg</a>

	 	&nbsp;&bull;&nbsp; <a href="http://validator.w3.org/check/referer">HTML5</a>

	 	&nbsp;&bull;&nbsp; <a href="http://jigsaw.w3.org/css-validator/">CSS3</a>
      </p>
    </footer>

  </body>
</html>
#+END_HTML

** Year Overview

FIXXME

** Tag

FIXXME

** Permanent

FIXXME

* Local Variables                                                  :noexport:
# Local Variables:
# mode: auto-fill
# mode: flyspell
# eval: (ispell-change-dictionary "en_US")
# End:
