## Time-stamp: <2016-11-06 18:15:18 vk>
## -*- coding: utf-8; mode: org; -*-
## This file is best viewed with GNU Emacs Org-mode: http://orgmode.org/


* README

This file contains the format templates of your blog.

lazyblorg needs a template file (command line parameter ~--template~)
which holds the output format definitions. It is using (only) the
heading which meets *all* of the following requirements:

- named ~Templates~
- is marked as ~DONE~
- tagged with ~:blog:~
- contains the unique ID property ~lazyblorg-templates~
- contains a ~:LOGBOOK:~ drawer with a time-stamp for being set to a
  ~DONE~ state

(Besides the name ~Templates~ those are the very same criteria for a
blog entry in general, by the way.)

This way, you can switch between different formats by using different
files (using different template files) or different headings within
this file (renaming first level headings and IDs; not recommended),
respectively.

The format templates are located in a heading hierarchy within the
~Templates~ heading. The hierarchy should be self explaining for
you. Please *do not modify headings* since lazyblorg is looking for
their exact form - at least for the first two levels.

Within a heading, each format template is defined in a HTML [[http://orgmode.org/manual/Working-With-Source-Code.html#Working-With-Source-Code][babel
block]].  Its name corresponds to the internal lazyblorg definition. So
please *do not modify the name strings* otherwise lazyblorg gets very
sad!

Within a format template, you will see strings like ~#FOO#~. These
place holder strings will get replaced by your content. If you modify
those, lazyblorg is not able to replace them with your content: *do
not modify/remove/invent place holder strings* by yourself.

In between the format templates, you can write whatever you want
unless it is no babel block of type ~html~: lazyblorg will ignore
these in-between notes.

For documentation about the implemented elements: see
id:implemented-org-elements in [[file:../dev/lazyblorg.org]]

Have fun with modifying lazyblorg to your requirements!

* DONE Templates                                                                  :lb_templates:blog:
:PROPERTIES:
:CREATED:  [2014-12-26 Fri 16:09]
:END:
:LOGBOOK:
- State "DONE"       from "DONE"       [2013-08-21 Wed 17:50]
:END:
:PROPERTIES:
:ID: lazyblorg-templates
:CREATED:  [2013-08-21 Wed 17:50]
:END:

** General elements

*** Sidebar

#+NAME: common-sidebar
#+BEGIN_EXPORT HTML

  <a id="show-sidebar-text" href="#show-sidebar">Show Sidebar</a>
  <div class="sidebar toggle-sidebar">
     <div class="search">
       <iframe id="search-big" src="//duckduckgo.com/search.html?width=140&site=karl-voit.at&prefill=Search%20blog"></iframe>
       <iframe id="search-narrow" src="//duckduckgo.com/search.html?width=70&k1=-1&k2=s&site=karl-voit.at&prefill=Search"></iframe>
       <br/>
     </div>
     <ul>
     <li>TBD: Archive</li>
     <li><a href="/">Recent articles</a></li>
     <li>[[id:2014-03-09-about][About this blog]]</li>
     <li>TBD: How to use this blog efficiently</li>
     <li><a href="//Karl-Voit.at/feeds/lazyblorg-all.atom_1.0.links-only.xml">Follow/subscribe links</a></li>
     <li><a href="//Karl-Voit.at/feeds/lazyblorg-all.atom_1.0.links-and-content.xml">Follow/subscribe content</a></li>
     <li>TBD: Per Tag Feeds</li>
     </ul>
  </div>

#+END_EXPORT

*** Sections

- #SECTION-TITLE#: title of the next heading/section
- #SECTION-LEVEL#: relative level of the next heading/section

#+NAME: section-begin
#+BEGIN_EXPORT HTML

	  <header><h#SECTION-LEVEL# class="section-title">#SECTION-TITLE#</h#SECTION-LEVEL#></header>

#+END_EXPORT
*** Paragraph

- #PAR-CONTENT#

#+NAME: paragraph
#+BEGIN_EXPORT HTML

<p>

#PAR-CONTENT#

</p>

#+END_EXPORT

*** Lists

#+NAME: ul-begin
#+BEGIN_EXPORT HTML
	  <ul>
#+END_EXPORT

- #CONTENT#: text of the list item

#+NAME: ul-item
#+BEGIN_EXPORT HTML
	    <li>#CONTENT#</li>
#+END_EXPORT

#+NAME: ul-end
#+BEGIN_EXPORT HTML
	  </ul>
#+END_EXPORT

*** Pre-formatted text

Without name/label:

#+NAME: pre-begin
#+BEGIN_EXPORT HTML

	  <pre>
#+END_EXPORT

#+NAME: pre-end
#+BEGIN_EXPORT HTML
	  </pre>

#+END_EXPORT

With name/label:

#+NAME: named-pre-begin
#+BEGIN_EXPORT HTML

<p>

    #NAME#
	  <pre>
#+END_EXPORT

#+NAME: named-pre-end
#+BEGIN_EXPORT HTML
	  </pre>

</p>
#+END_EXPORT

*** SRC blocks (not HTML)

Without name/label:

#+NAME: src-begin
#+BEGIN_EXPORT HTML

	  <div class="example_code">
	  <pre>
#+END_EXPORT

#+NAME: src-end
#+BEGIN_EXPORT HTML
	  </pre>
    </div>

#+END_EXPORT

With name/label:

#+NAME: named-src-begin
#+BEGIN_EXPORT HTML

<p>

    #NAME#
	  <div class="example_code">
	  <pre>
#+END_EXPORT

#+NAME: named-src-end
#+BEGIN_EXPORT HTML
	  </pre>
    </div>

</p>
#+END_EXPORT

*** HTML blocks

- #NAME#: Org-mode name of the block

#+NAME: html-begin
#+BEGIN_EXPORT HTML

<p>

    #NAME#
	  <div class="example_code">
#+END_EXPORT

#+NAME: html-end
#+BEGIN_EXPORT HTML
	  </div>

</p>

#+END_EXPORT

*** QUOTE blocks

#+NAME: blockquote-begin
#+BEGIN_EXPORT HTML

<blockquote>
#+END_EXPORT

#+NAME: blockquote-end
#+BEGIN_EXPORT HTML
</blockquote>

#+END_EXPORT

*** ignore me

#+NAME:
#+BEGIN_EXPORT HTML
#+END_EXPORT

#+NAME:
#+BEGIN_EXPORT HTML
#+END_EXPORT


** Persistent

*** Entry Page

**** Header

- #BLOGNAME#: short name of the blog
- #ABOUT-BLOG#: a line of text which describes the blog in general
- #COMMON-SIDEBAR# : the sidebar conentent which is shared on all pages
- #ARTICLE-ID#: Org-mode ID property of the blog entry


#+NAME: entrypage-header
#+BEGIN_EXPORT HTML
  <!DOCTYPE html>
  <html xmlns="http://www.w3.org/1999/xhtml">
  <head>
  <meta charset="UTF-8">
  <meta name="author" content="Karl Voit" />
  <meta name="generator" content="lazyblorg" />
  <meta name="orgmode-id" content="#ARTICLE-ID#" />
  <link rel="stylesheet" title="public voit Standard CSS Style"
        href="//Karl-Voit.at/public_voit.css" type="text/css" media="screen"  />

  <!-- WARNING: This page is written in HTML5 and might not be displayed correctly in old browsers. -->

  <title>Public Voit - Homepage of Karl Voit</title>
  </head>

  <body class="persistent-body">

  <header class="persistent-header">

      <nav class="entrypage-article-header-nav">
        <span class="breadcrumbs">
          <img src="//Karl-Voit.at/images/public-voit_logo.svg" alt="public voit logo" width="350" style="vertical-align:middle;"><span style="padding-top:1em;">
        </span>
      </nav>

  </header>

  #COMMON-SIDEBAR#

  <div class="entry-page-greetings">
  <p>

    This is the home-page of Karl Voit.

  </p>

  <p>

    Please notice: <a href="2014/01/30/public-voit-beta/">This site is under constant development</a>. See
    <a href="https://github.com/novoid/lazyblorg/blob/master/dev/lazyblorg.org#23-implemented-org-mode-elements">current status of the blogging software</a> and
    <a href="https://github.com/novoid/lazyblorg/blob/master/dev/lazyblorg.org#1-issue-tracking">the next steps</a>.
  </p>

  <p>

    Recent articles/updates:

  </p>
  </div>

#+END_EXPORT

**** Article-Preview

- #ARTICLE-TITLE#: heading/title of the blog article
- #ARTICLE-URL#: URL of the blog article
- #ARTICLE-YEAR#: four digit year of the article (folder path)
- #ARTICLE-MONTH#: two digit month of the article (folder path)
- #ARTICLE-DAY#: two digit day of the article (folder path)
- #ARTICLE-PUBLISHED-HTML-DATETIME#: time-stamp of publishing in HTML
  date-time format (e.g., ~2011-10-30T15:00+02:00~)
- #ARTICLE-PUBLISHED-HUMAN-READABLE#: time-stamp of publishing in
  human readable format (e.g., ~2011-10-30T15:00~)
- #ARTICLE-TEASER#: First lines up to the first heading or <hr>-element

#+NAME: article-preview-header
#+BEGIN_EXPORT HTML


<article class="entry-page-article">
#+END_EXPORT

#+NAME: article-preview-tags-begin
#+BEGIN_EXPORT HTML

	  <aside>
	    <ul class="entry-page-article-tags">
#+END_EXPORT

- #TAGNAME#: string of a tag

#+NAME: article-preview-usertag
#+BEGIN_EXPORT HTML
                <li><a class="usertag" href="//Karl-Voit.at/tags/#TAGNAME#/">#TAGNAME#</a></li>

#+END_EXPORT

#+NAME: article-preview-autotag
#+BEGIN_EXPORT HTML
                <li><a class="autotag" href="//Karl-Voit.at/tags/#TAGNAME#/">#TAGNAME#</a></li>

#+END_EXPORT


#+NAME: article-preview-tags-end
#+BEGIN_EXPORT HTML

	    </ul>
	  </aside>
#+END_EXPORT


#+NAME: article-preview-begin
#+BEGIN_EXPORT HTML

<h1><a href="#ARTICLE-URL#">#ARTICLE-YEAR#-#ARTICLE-MONTH#-#ARTICLE-DAY#: #ARTICLE-TITLE#</a></h1>

#ARTICLE-TEASER#

#+END_EXPORT

#+NAME: article-preview-more
#+BEGIN_EXPORT HTML
<p>
<a href="#ARTICLE-URL#" class="article-preview-more">Read the whole article&nbsp;...</a>
</p>
#+END_EXPORT

#+NAME: article-preview-end
#+BEGIN_EXPORT HTML


</article>


#+END_EXPORT

**** Footer

- #BLOGNAME#: short name of the blog
- #ABOUT-BLOG#: a line of text which describes the blog in general

#+NAME: entrypage-footer
#+BEGIN_EXPORT HTML


    <footer>
      <p><i>[[id:2014-03-09-about][#ABOUT-BLOG#]]</i> is authored in <a href="//orgmode.org">Org-mode</a> and generated by <a href="https://github.com/novoid/lazyblorg">lazyblorg</a>

	 	&nbsp;&bull;&nbsp; <a href="//validator.w3.org/check/referer">HTML5</a>

	 	&nbsp;&bull;&nbsp; <a href="//jigsaw.w3.org/css-validator/">CSS3</a>
      </p>
    </footer>

  </body>
</html>
#+END_EXPORT


*** Other Persistent Pages

**** Header

- #ARTICLE-TITLE#: heading/title of the blog article
- #ARTICLE-ID#: Org-mode ID property of the blog entry

#+NAME: persistent-header
#+BEGIN_EXPORT HTML
  <!DOCTYPE html>
  <html xmlns="http://www.w3.org/1999/xhtml">
  <head>
  <meta charset="UTF-8">
  <meta name="author" content="Karl Voit" />
  <meta name="generator" content="lazyblorg" />
  <meta name="orgmode-id" content="#ARTICLE-ID#" />
  <link rel="stylesheet" title="public voit Standard CSS Style"
        href="//Karl-Voit.at/public_voit.css" type="text/css" media="screen"  />

  <!-- WARNING: This page is written in HTML5 and might not be displayed correctly in old browsers. -->

      <title>#ARTICLE-TITLE#</title>

  </head>

#+END_EXPORT

**** Top of Article

- #BLOGNAME#: short name of the blog
- #ARTICLE-YEAR#: four digit year of the article (folder path)
- #ARTICLE-MONTH#: two digit month of the article (folder path)
- #ARTICLE-DAY#: two digit day of the article (folder path)
- #ARTICLE-PUBLISHED-HTML-DATETIME#: time-stamp of publishing in HTML
  date-time format (e.g., 2011-10-30T15:00+02:00)
- #ARTICLE-PUBLISHED-HUMAN-READABLE#: time-stamp of publishing in
  human readable format (e.g., 2011-10-30T15:00)
- #COMMON-SIDEBAR# : the sidebar conentent which is shared on all pages

#+NAME: persistent-header-begin
#+BEGIN_EXPORT HTML
  <body>

    <div class="common-orgsource"><a href="source.org.txt">&#960;</a></div>

	<header>

	  <nav class="persistent-article-header-nav">
	    <span class="breadcrumbs">
	      <a href="../"><img src="//Karl-Voit.at/images/public-voit_logo.svg" alt="public voit logo" width="350" style="vertical-align:middle;"></a>
	    </span>
	  </nav>

#+END_EXPORT

#+NAME: persistent-header-end
#+BEGIN_EXPORT HTML

	  <h1 class="common-article-header-title">#ARTICLE-TITLE#</h1>

	</header>

    #COMMON-SIDEBAR#

    <article class="common-article">

#+END_EXPORT

#+NAME: persistent-end
#+BEGIN_EXPORT HTML

    </article>

#+END_EXPORT

**** Footer

- #ABOUT-BLOG#: a line of text which describes the blog in general

#+NAME: persistent-footer
#+BEGIN_EXPORT HTML
	  <aside class="published-on">
	    Published on <time datetime="#ARTICLE-PUBLISHED-HTML-DATETIME#">#ARTICLE-PUBLISHED-HUMAN-READABLE#</time>
	  </aside>

   <p class="email-comment">
      <a href="mailto:publicvoit-comment@Karl-Voit.at?subject=#ARTICLE-ID#%20comment:%20&body=Please%20do%20not%20remove%20'#ARTICLE-ID#%20comment:'%20in%20subject%20and%20please%20tell%20me%20whether%20or%20not%20it%20is%20OK%20to%20add%20your%20comment%20and%2For%20your%20email%20address%20to%20the%20blog%20entry!">Comment via email</a> or via <a href="//disqus.com">Disqus</a> comments below:
   </p>

    <div id="disqus_thread"></div>
    <div id="disqus_loader" style="text-align: center">
      <!-- stolen from http://blog.yjl.im/2012/04/let-your-readers-decide-when-to-load.html -->
      <button onclick="load_disqus()">Load Disqus Comments</button>
      <script>
        function load_disqus()
        {
          var dsq = document.createElement('script');
          dsq.type = 'text/javascript';
          dsq.async = true;
          dsq.src = "//publicvoit.disqus.com/embed.js";
          var disqus_identifier = '#ARTICLE-ID#';
          (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
          var ldr = document.getElementById('disqus_loader');
          ldr.parentNode.removeChild(ldr);
        }
      </script>
    </div>
    <noscript>Please enable JavaScript to view the <a href="//disqus.com/?ref_noscript">Disqus comments.</a></noscript>

    <footer>
      <p><i>[[id:2014-03-09-about][#ABOUT-BLOG#]]</i> is authored in <a href="//orgmode.org">Org-mode</a> and generated by <a href="https://github.com/novoid/lazyblorg">lazyblorg</a>

	 	&nbsp;&bull;&nbsp; <a href="//validator.w3.org/check/referer">HTML5</a>

	 	&nbsp;&bull;&nbsp; <a href="//jigsaw.w3.org/css-validator/">CSS3</a>
      </p>
    </footer>

  </body>
</html>
#+END_EXPORT


** Article

*** Header

- #ARTICLE-TITLE#: heading/title of the blog article
- #ARTICLE-ID#: Org-mode ID property of the blog entry

#+NAME: article-header
#+BEGIN_EXPORT HTML
  <!DOCTYPE html>
  <html xmlns="http://www.w3.org/1999/xhtml">
  <head>
  <meta charset="UTF-8">

  <meta name="author" content="Karl Voit" />
  <meta name="generator" content="lazyblorg" />
  <meta name="description" content="#ARTICLE-TITLE#" />
  <meta name="orgmode-id" content="#ARTICLE-ID#" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:site" content="@n0v0id" />
  <meta name="twitter:creator" content="@n0v0id" />
  <meta name="twitter:title" content="public voit" />
  <meta name="twitter:description" content="#ARTICLE-TITLE#" />
  <meta name="twitter:image" content="http://Karl-Voit.at/images/public-voit_T_logo_200x200.png" />

  <meta property="og:type" content="article" />
  <meta property="og:title" content="public voit" />
  <meta property="og:description" content="#ARTICLE-TITLE#" />
  <meta property="og:image" content="http://karl-voit.at/images/public-voit_T_logo_200x200.png" />
  <meta property="og:site_name" content="public voit - Web-page of Karl Voit">
  <meta property="article:published_time" content="#ARTICLE-PUBLISHED-HTML-DATETIME#" />
  <meta property="article:author" content="Karl Voit" />

  <link rel="stylesheet" title="public voit Standard CSS Style"
        href="//Karl-Voit.at/public_voit.css" type="text/css" media="screen"  />

  <!-- WARNING: This page is written in HTML5 and might not be displayed correctly in old browsers. -->

      <!-- link rel="stylesheet" type="text/css" href="../../../../style.css" / -->
      <title>#ARTICLE-TITLE#</title>

  </head>
#+END_EXPORT

*** Top of Article

- #BLOGNAME#: short name of the blog
- #ARTICLE-YEAR#: four digit year of the article (folder path)
- #ARTICLE-MONTH#: two digit month of the article (folder path)
- #ARTICLE-DAY#: two digit day of the article (folder path)
- #ARTICLE-PUBLISHED-HTML-DATETIME#: time-stamp of publishing in HTML
  date-time format (e.g., 2011-10-30T15:00+02:00)
- #ARTICLE-PUBLISHED-HUMAN-READABLE#: time-stamp of publishing in
  human readable format (e.g., 2011-10-30T15:00)
- #COMMON-SIDEBAR# : the sidebar conentent which is shared on all pages

#+NAME: article-header-begin
#+BEGIN_EXPORT HTML
  <body>

    <div class="common-orgsource"><a href="source.org.txt">&#960;</a></div>


	<header>

	  <nav class="temporal-article-header-nav">
	    <span class="breadcrumbs">
	      <a href="../../../../"><img src="//karl-voit.at/images/public-voit_logo.svg" alt="public voit logo" width="350" style="vertical-align:middle;"></a><span style="padding-top:1em;">&nbsp;&nbsp;&nbsp;&nbsp;&raquo;
	      #ARTICLE-YEAR#&nbsp;&ndash;&nbsp;#ARTICLE-MONTH#&nbsp;&ndash;&nbsp;#ARTICLE-DAY#</span>
	      <!-- a href="../../../">#ARTICLE-YEAR#</a>&nbsp;&ndash;&nbsp;<a href="../../">#ARTICLE-MONTH#</a>&nbsp;&ndash;&nbsp;<a href="../">#ARTICLE-DAY#</a -->
	    </span>
	  </nav>

#+END_EXPORT


#+NAME: article-tags-begin
#+BEGIN_EXPORT HTML
	  <aside class="common-tags">
	    <ul>

#+END_EXPORT

- #TAGNAME#: string of a tag

#+NAME: article-usertag
#+BEGIN_EXPORT HTML
                <li><a class="usertag" href="//Karl-Voit.at/tags/#TAGNAME#/">#TAGNAME#</a></li>

#+END_EXPORT

#+NAME: article-autotag
#+BEGIN_EXPORT HTML
                <li><a class="autotag" href="//Karl-Voit.at/tags/#TAGNAME#/">#TAGNAME#</a></li>

#+END_EXPORT

#+NAME: article-tags-end
#+BEGIN_EXPORT HTML
	    </ul>
	  </aside>

#+END_EXPORT



#+NAME: article-header-end
#+BEGIN_EXPORT HTML

	  <h1 class="common-article-header-title">#ARTICLE-TITLE#</h1>

	</header>

  #COMMON-SIDEBAR#

  <article class="common-article">

#+END_EXPORT

#+NAME: article-end
#+BEGIN_EXPORT HTML


  </article>

#+END_EXPORT

*** Footer

- #ABOUT-BLOG#: a line of text which describes the blog in general

#+NAME: article-footer
#+BEGIN_EXPORT HTML
	  <aside class="published-on">
	    Published on <time datetime="#ARTICLE-PUBLISHED-HTML-DATETIME#">#ARTICLE-PUBLISHED-HUMAN-READABLE#</time>
	  </aside>

   <p class="email-comment">
      <a href="mailto:publicvoit-comment@Karl-Voit.at?subject=#ARTICLE-ID#%20comment:%20&body=Please%20do%20not%20remove%20'#ARTICLE-ID#%20comment:'%20in%20subject%20and%20please%20tell%20me%20whether%20or%20not%20it%20is%20OK%20to%20add%20your%20comment%20and%2For%20your%20email%20address%20to%20the%20blog%20entry!">Comment via email</a> or via <a href="//disqus.com">Disqus</a> comments below:
   </p>

    <div id="disqus_thread"></div>
    <div id="disqus_loader" style="text-align: center">
      <!-- stolen from http://blog.yjl.im/2012/04/let-your-readers-decide-when-to-load.html -->
      <button onclick="load_disqus()">Load Disqus Comments</button>
      <script>
        function load_disqus()
        {
          var dsq = document.createElement('script');
          dsq.type = 'text/javascript';
          dsq.async = true;
          dsq.src = "//publicvoit.disqus.com/embed.js";
          var disqus_identifier = '#ARTICLE-ID#';
          (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
          var ldr = document.getElementById('disqus_loader');
          ldr.parentNode.removeChild(ldr);
        }
      </script>
    </div>
    <noscript>Please enable JavaScript to view the <a href="//disqus.com/?ref_noscript">Disqus comments.</a></noscript>

    <footer>
      <p><i>[[id:2014-03-09-about][#ABOUT-BLOG#]]</i> is authored in <a href="//orgmode.org">Org-mode</a> and generated by <a href="https://github.com/novoid/lazyblorg">lazyblorg</a>

	 	&nbsp;&bull;&nbsp; <a href="//validator.w3.org/check/referer">HTML5</a>

	 	&nbsp;&bull;&nbsp; <a href="//jigsaw.w3.org/css-validator/">CSS3</a>
      </p>
    </footer>

  </body>
</html>
#+END_EXPORT


** Tag Pages

Pages that describe a tag. Corresponding Org-mode entries must have:
- heading is a single word: the tag itself
- tags =blog= and =lb_tag= set
- =ID= set in properties
- marked as =DONE=

*** Header

- #ARTICLE-TITLE#: heading/title of the blog article
- #ARTICLE-ID#: Org-mode ID property of the blog entry

#+NAME: tagpage-header
#+BEGIN_EXPORT HTML
  <!DOCTYPE html>
  <html xmlns="http://www.w3.org/1999/xhtml">
  <head>
  <meta charset="UTF-8">

  <meta name="author" content="Karl Voit" />
  <meta name="generator" content="lazyblorg" />
  <meta name="description" content="Tag page for tag #ARTICLE-TITLE#" />
  <meta name="orgmode-id" content="#ARTICLE-ID#" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:site" content="@n0v0id" />
  <meta name="twitter:creator" content="@n0v0id" />
  <meta name="twitter:title" content="public voit" />
  <meta name="twitter:description" content="Tag page for tag #ARTICLE-TITLE#" />
  <meta name="twitter:image" content="http://karl-voit.at/images/public-voit_T_logo_200x200.png" />

  <meta property="og:type" content="article" />
  <meta property="og:title" content="public voit" />
  <meta property="og:description" content="Tag page for tag #ARTICLE-TITLE#" />
  <meta property="og:image" content="http://karl-voit.at/images/public-voit_T_logo_200x200.png" />
  <meta property="og:site_name" content="public voit - Web-page of Karl Voit">
  <meta property="article:published_time" content="#ARTICLE-PUBLISHED-HTML-DATETIME#" />
  <meta property="article:author" content="Karl Voit" />

  <link rel="stylesheet" title="public voit Standard CSS Style"
        href="//Karl-Voit.at/public_voit.css" type="text/css" media="screen"  />

  <!-- WARNING: This page is written in HTML5 and might not be displayed correctly in old browsers. -->

      <!-- link rel="stylesheet" type="text/css" href="../../../../style.css" / -->
      <title>The Tag &laquo;#ARTICLE-TITLE#&raquo;</title>

  </head>
#+END_EXPORT

*** Top of Article

- #BLOGNAME#: short name of the blog
- #ARTICLE-YEAR#: four digit year of the article (folder path)
- #ARTICLE-MONTH#: two digit month of the article (folder path)
- #ARTICLE-DAY#: two digit day of the article (folder path)
- #ARTICLE-PUBLISHED-HTML-DATETIME#: time-stamp of publishing in HTML
  date-time format (e.g., 2011-10-30T15:00+02:00)
- #ARTICLE-PUBLISHED-HUMAN-READABLE#: time-stamp of publishing in
  human readable format (e.g., 2011-10-30T15:00)
- #COMMON-SIDEBAR# : the sidebar conentent which is shared on all pages

#+NAME: tagpage-header-begin
#+BEGIN_EXPORT HTML
  <body>

    <div class="common-orgsource"><a href="source.org.txt">&#960;</a></div>


	<header>

	  <nav class="temporal-article-header-nav">
	    <span class="breadcrumbs">
	      <a href="../../../../"><img src="//karl-voit.at/images/public-voit_logo.svg" alt="public voit logo" width="350" style="vertical-align:middle;"></a><span style="padding-top:1em;">&nbsp;&nbsp;&nbsp;&nbsp;&raquo;
	      #ARTICLE-YEAR#&nbsp;&ndash;&nbsp;#ARTICLE-MONTH#&nbsp;&ndash;&nbsp;#ARTICLE-DAY#</span>
	      <!-- a href="../../../">#ARTICLE-YEAR#</a>&nbsp;&ndash;&nbsp;<a href="../../">#ARTICLE-MONTH#</a>&nbsp;&ndash;&nbsp;<a href="../">#ARTICLE-DAY#</a -->
	    </span>
	  </nav>

#+END_EXPORT


#+NAME: tagpage-tags-begin
#+BEGIN_EXPORT HTML
	  <aside class="common-tags">
	    <ul>

#+END_EXPORT

- #TAGNAME#: string of a tag

#+NAME: tagpage-usertag
#+BEGIN_EXPORT HTML
                <li><a class="usertag" href="//Karl-Voit.at/tags/#TAGNAME#/">#ARTICLE_TITLE#</a></li>

#+END_EXPORT

#+NAME: tagpage-autotag
#+BEGIN_EXPORT HTML
                <li><a class="autotag" href="//Karl-Voit.at/tags/#TAGNAME#/">#TAGNAME#</a></li>

#+END_EXPORT

#+NAME: tagpage-tags-end
#+BEGIN_EXPORT HTML
	    </ul>
	  </aside>

#+END_EXPORT

#+NAME: tagpage-header-end
#+BEGIN_EXPORT HTML

	  <h1 class="common-article-header-title">Tag Page for the Tag "#ARTICLE-TITLE#"</h1>

	</header>

  #COMMON-SIDEBAR#

  <article class="common-article">

#+END_EXPORT

#+NAME: tagpage-end
#+BEGIN_EXPORT HTML

  <hr />

  <p>
  All articles tagged with #ARTICLE-TITLE#:
  </p>

  <p>
  #TAG-PAGE-LIST#
  </p>

  </article>

#+END_EXPORT

*** Footer

I'm re-using article-footer.

** Day Overview

FIXXME

** Month Overview

*** Header

- #BLOGNAME#: short name of the blog
- #YEAR#: four digit year
- #MONTH-LONGNAME#: name of the month like "January" or "February"
- #MONTH-SHORTNAME#: three letter name of the month like "Jan" or "Feb"
- #MONTH-TWODIGITNUMBER#: number of the month like "01" or "02"

#+NAME: month-header
#+BEGIN_EXPORT HTML
  <!DOCTYPE html>
  <html xmlns="http://www.w3.org/1999/xhtml">
  <head>
  <meta charset="UTF-8">
  <meta name="author" content="Karl Voit" />
  <meta name="generator" content="lazyblorg" />
  <link rel="stylesheet" title="public voit Standard CSS Style"
        href="//Karl-Voit.at/public_voit.css" type="text/css" media="screen"  />

  <!-- WARNING: This page is written in HTML5 and might not be displayed correctly in old browsers. -->

  <title>#BLOGNAME#: #YEAR#-#MONTH-TWODIGITNUMBER#</title>
  </head>

  <body>

  <article class="month-overview">

	<header>

	  <nav class="month-overview-header-nav">
	    <span class="breadcrumbs">
	      <a href="../../"><img src="//karl-voit.at/images/public-voit_logo.svg" alt="public voit logo" width="350" style="vertical-align:middle;"></a><span style="padding-top:1em;">&nbsp;&nbsp;&nbsp;&nbsp;&raquo;
	      #YEAR#&nbsp;&ndash;&nbsp;#MONTH-TWODIGITNUMBER#</span>
	    </span>
	  </nav>

	  <h1 class="article-title">#YEAR#-#MONTH-TWODIGITNUMBER#</h1>

	</header>

  <p><ul class="month-body">

#+END_EXPORT

*** Article-Link

- #ARTICLE-TITLE#: heading/title of the blog article
- #ARTICLE-URL#: URL of the blog article
- #ARTICLE-YEAR#: four digit year of the article (folder path)
- #ARTICLE-MONTH#: two digit month of the article (folder path)
- #ARTICLE-DAY#: two digit day of the article (folder path)
- #ARTICLE-PUBLISHED-HTML-DATETIME#: time-stamp of publishing in HTML
  date-time format (e.g., 2011-10-30T15:00+02:00)
- #ARTICLE-PUBLISHED-HUMAN-READABLE#: time-stamp of publishing in
  human readable format (e.g., 2011-10-30T15:00)

#+NAME: article-list-link
#+BEGIN_EXPORT HTML
<li><a href="#ARTICLE-URL#">#ARTICLE-YEAR#-#ARTICLE-MONTH#-#ARTICLE-DAY#: #ARTICLE-TITLE#</a></li>
#+END_EXPORT

*** Footer

- #BLOGNAME#: short name of the blog
- #YEAR#: four digit year
- #MONTH-LONGNAME#: name of the month like "January" or "February"
- #MONTH-SHORTNAME#: three letter name of the month like "Jan" or "Feb"
- #MONTH-TWODIGITNUMBER#: number of the month like "01" or "02"

#+NAME: month-footer
#+BEGIN_EXPORT HTML

    </ul></p>
    </article>

    <footer>
      <p><i>[[id:2014-03-09-about][#ABOUT-BLOG#]]</i> is authored in <a href="//orgmode.org">Org-mode</a> and generated by <a href="https://github.com/novoid/lazyblorg">lazyblorg</a>

	 	&nbsp;&bull;&nbsp; <a href="//validator.w3.org/check/referer">HTML5</a>

	 	&nbsp;&bull;&nbsp; <a href="//jigsaw.w3.org/css-validator/">CSS3</a>
      </p>
    </footer>

  </body>
</html>
#+END_EXPORT

** Year Overview

FIXXME

* Local Variables                                                                          :noexport:
:PROPERTIES:
:CREATED:  [2014-12-26 Fri 16:09]
:END:
# Local Variables:
# mode: auto-fill
# mode: flyspell
# eval: (ispell-change-dictionary "en_US")
# End:
